### ISSUE TITLE
Extreme CPU Usage on small cluster

### ISSUE THREAD

**Issue by Bonn93** [k3s-io/k3s#10396]
**Environmental Info:**
K3s Version: 
```
k3s version v1.30.1+k3s1 (80978b5b)
go version go1.22.2
```

Node(s) CPU architecture, OS, and Version: 
```
Linux k3s-server.internal.self-hosted.io 4.18.0-513.24.1.el8_9.x86_64 #1 SMP Thu Apr 4 18:13:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
k3s server has extremely high CPU usage, even scaling pods back to 0 there's no change. A 4 core/16GB RAM machine has a load average of and often spikes to 50/60!
```
load average: 13.42, 20.74, 22.08
```

**Steps To Reproduce:**
k3s has been running for a while with the upgrade controller/operator.

**Expected behavior:**
CPU is within sane numbers

**Actual behavior:**
Extremely high CPU usage, slow API response times and often timeouts. Appears to spam /var/log/messages with `trace` logging.

**Additional context / logs:**
Nodes have NVMe local drives. The `k3s-server` process is using 400%, there's no other large processes on the system. It has high %USR with about 20% SYS/Kernel time. The state.db is also 12GB~ and SQLLite fails to vacuum. Cluster age is 270d.

**Comment by Bonn93** [comment]
Okay, this is certainly SQLLite related. Migrating to etcd the cluster has returned to normal levels by adding `--cluster-init` to the systemd unit, however the `Trace:` logging is still present. 

The server is now at 0.4 1m load average and responding to requests quickly. The SQLLite vacuum did not do anything, but migrating to etcd did. Trying to set `-v=0` in the systemd unit doesn't seem to have an effect on the logs either.

Happy to close as the root issue seems clear.

**Comment by Bonn93** [comment]
Yeah, I've bootstrapped a few smaller clusters recently and the smaller ones with the non ha control plane all get like this in the long run. Doing the init flag and converting to etcd fixes and the other clusters long run are all happy. 

I just bootstrap with etcd single node now. I don't think sqllite is the best choice.

**Comment by paketb0te** [comment]
@Bonn93 thx, that helps a lot :)

**Comment by Bonn93** [comment]
@Vashiru see this, you stop the service and add this flag. https://docs.k3s.io/datastore/ha-embedded#existing-single-node-clusters

**Comment by Vashiru** [comment]
@Bonn93 Much, much, much appreciated! I've been pulling my hair out over my Raspberry Pi being so unstable for months now. And I really wasn't looking forward to reinstalling the whole thing either. This has been a way easier solution.

Next thing is to figure out if my zigbee network was in fact as unstable as it seemed, or if home-assistant just decided to give up on most nodes and processing signals from it due to the high load... But for now I'm enjoying my load numbers being < 1 rather than 15-30! 😄

**Comment by paketb0te** [comment]
> Any chance you can elaborate on that reinstall process? Is there a way to like convert it to etcd or is this a case of grab a back-up of your deployments, uninstall k3s entirely and re-apply all yaml files?

We run multiple identical clusters and have all manifests in git, so we just destroyed the clusters and re-created them from scratch with etcd...

**Comment by fboerman** [comment]
@Bonn93 I added this flag and restarted the service, but now my cluster is endlessly hanging in startup and spawning this in the logs: error msg="Sending HTTP/2.0 503 response to 10.42.0.23:55220: starting with various ports and ips. what does that mean and how do I fix that?

**Comment by ogirardot** [comment]
@fboerman it is related, you can check the size of the sqlite database, mine was about 280Gb when it took 15min to boot, a vaccum improved the startup time

**Comment by anthonymag** [comment]
I've been running a 3 node cluster for several months, and to upgrade the kube version I reran the install script:
```
curl -sfL https://get.k3s.io | K3S_TOKEN='token' sh -s - server  --server https://mydomain.tld:6443
```

however CPU was running hot on all three for days after doing that even though everything was up. All nodes were on the new engine and displayed healthy with `kubectl get no`. I reran the above without `--server` and with `--cluster-init` on one node, then ran the above again on the other two nodes and the CPU seems happy again.
Since it was already in cluster mode doesn't that confirm I was already using etcd? I seem to have fixed the issue but not sure why that did the fix.
