### ISSUE TITLE
containerd process building from k3s costs more memory than building from containerd

### ISSUE THREAD

**Issue by volume-ji** [k3s-io/k3s#1117]
we know that starting k3s agent will have two processes: k3s main process and containerd process, actually, containerd process will cost more memory than real containerd from "https://github.com/containerd/containerd/releases". It seems the mechanism of reexec function will cost more memories if containerd start in this condition. it is a performance problem for edge computing scene.
the data comparison( I means using "./containerd" start process separately and collect statistics):
  unique containerd memory: 49348
  k3s  containerd memory:  83600

**Version:**

v1.0.0

**Describe the bug**

containerd cost more memories

**To Reproduce**

start containerd process separately and compare

**Expected behavior**

k3s containerd cost as little memory as possible because it is a unique sub process.

**Actual behavior**

**Additional context**

**Comment by volume-ji** [comment]
appreciated for any reply

**Comment by dweomer** [comment]
wouldn't most of the difference there be shared, resident?

**Comment by dweomer** [comment]
> wouldn't most of the difference there be shared, resident?

i mean, since the `k3s` and `containerd` processes are two separate invocations of the `k3s` executable i'd be surprised if your total memory usage on the system was lower with a separately compiled `containerd`

**Comment by volume-ji** [comment]
I guess reexec mechanism will integrate one binary, which can link other binary we need(containerd, ctr, crictl, etc), but containerd process have a same entrypoint with k3s,  containerd process will invoke reexec branch, which import other library  and pakcage k3s need but containerd do not need.

I mean if there is no containerd process separately other than all function(kubelet, containerd, flannel) embed into k3s process，which should cost less memory.

![image](https://user-images.githubusercontent.com/38492374/69471261-5649de00-0dd8-11ea-9fa5-d55e107bbaf2.png)

**Comment by volume-ji** [comment]
I mean k3s process and containerd subprocess have a same main() function, the different is containerd enter into reexec branch( if{} statement ), maybe import package use repeated memory?
of course this do minus disk space

**Comment by dweomer** [comment]
Yes, this makes the k3s binary rather large on disk but it should be less than if you compiled k3s without containerd, then the compiled containerd and then measure the combined total size. The k3s compiled with containerd should total at least a few MB less (de-duped go runtime).

Now, unless I am mistaken, two processes sourced from the same executable, regardless of whether or not they are on different branches of execution (implies different memory profiles), should use in total less memory because the OS can share the loaded code between them. Less memory in total when compared to the hypothesized k3s-without-containerd + containerd multi-executable scenario above.

Re-reading your responses, I think you agree with me. If not, I encourage you to run the same comparative experiment again but this time focus on total persistent disk used and total free memory.
