### ISSUE TITLE
Ubuntu and Ansible

### ISSUE THREAD

**Issue by tadas-subonis** [k3s-io/k3s#1225]
Does this ansible script work with Ubuntu LTS? https://github.com/rancher/k3s/tree/master/contrib/ansible

If not, what's missing?

**Comment by rgstephens** [comment]
I'm testing on Ubuntu 18.04.  I had to use the `--ask-become-pass` option otherwise I got an `Missing sudo password` error.

```
ansible-playbook site.yml --ask-become-pass
```

The script hangs on

```
k3s/node : Enable and check K3s service
```

I also updated the version in `inventory/group_vars/all.yml` to `k3s_version: v1.17.4+k3s1`

and I got an expected warning on the `Rebooting on Raspbian` Task and the `Test for Rapbian` succeeded.
