### ISSUE TITLE
agent unable to join master, error: Remotedialer proxy error"

### ISSUE THREAD

**Issue by ghost** [k3s-io/k3s#1267]
I am seeing following error where k3s agent is not joining to the master.

this use to work in older release like v0.6.1 version. But the same command doesn't work in any release after that.
Getting following error, for k3s-agent when its trying to come up.

I am running following k3s-agent command to join the master:
curl -sfL https://get.k3s.io | K3S_TOKEN=<token>  K3S_URL=https://<server-ip>:6443 sh -

This command works if I install k3s version for v0.6.1, but if I try the same command for say v1.0.0 or v0.8.0 , agent fail to join with following error.

vagrant@k3s-node-1:~$ systemctl status k3s-agent
● k3s-agent.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-03 09:57:52 UTC; 1min 45s ago
     Docs: https://k3s.io
  Process: 1773 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 1765 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 1774 (k3s-agent)
    Tasks: 17
   CGroup: /system.slice/k3s-agent.service
           ├─1774 /usr/local/bin/k3s agent
           └─1795 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/li

Jan 03 09:59:20 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:20.140256555Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.2.15:6443: connect: connect
Jan 03 09:59:25 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:25.141511527Z" level=info msg="Connecting to proxy" url="wss://10.0.2.15:6443/v1-k3s/connect"
Jan 03 09:59:25 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:25.142615252Z" level=error msg="Failed to connect to proxy" error="dial tcp 10.0.2.15:6443: connect: conne
Jan 03 09:59:25 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:25.142807041Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.2.15:6443: connect: connect
Jan 03 09:59:30 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:30.143895628Z" level=info msg="Connecting to proxy" url="wss://10.0.2.15:6443/v1-k3s/connect"
Jan 03 09:59:30 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:30.144787291Z" level=error msg="Failed to connect to proxy" error="dial tcp 10.0.2.15:6443: connect: conne
Jan 03 09:59:30 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:30.144959028Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.2.15:6443: connect: connect
Jan 03 09:59:35 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:35.146369037Z" level=info msg="Connecting to proxy" url="wss://10.0.2.15:6443/v1-k3s/connect"
Jan 03 09:59:35 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:35.147026791Z" level=error msg="Failed to connect to proxy" error="dial tcp 10.0.2.15:6443: connect: conne
Jan 03 09:59:35 k3s-node-1 k3s[1774]: time="2020-01-03T09:59:35.147236984Z" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.2.15:6443: connect: connect
lines 1-22/22 (END)

**Comment by pnkjtr** [comment]
Successful case:

vagrant@k3s-node-1:~$ k3s --version
k3s version v0.6.1 (7ffe802a)


I am getting following logs for k3s-agent for k3s version: v0.6.1
and the node joins successfully to master.  on master, I can see the node in "kubectl get nodes" output.

vagrant@k3s-node-1:~$ systemctl status k3s-agent
● k3s-agent.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-03 10:15:39 UTC; 13min ago
     Docs: https://k3s.io
  Process: 1787 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 1778 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 1788 (k3s-agent)
    Tasks: 45
   CGroup: /system.slice/k3s-agent.service
           ├─1788 /usr/local/bin/k3s agent
           ├─1807 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /
           ├─2099 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/73704e1d8af892af629e6306
           ├─2123 /pause
           ├─2166 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/abf6006be3e81fc4da6ee485
           ├─2187 /bin/sh /usr/bin/entry
           ├─2232 containerd-shim -namespace k8s.io -workdir /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v1.linux/k8s.io/4b5ec1168a4e27e52686d2af
           └─2257 /bin/sh /usr/bin/entry

Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.893354    1788 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.894491    1788 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --ran
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.897633    1788 iptables.go:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.1.0/24 -j RETURN
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.900976    1788 iptables.go:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --ra
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.901523    1788 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.908600    1788 iptables.go:155] Adding iptables rule: -d 10.42.0.0/16 -j ACCEPT
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.910265    1788 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --rando
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.915114    1788 iptables.go:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.1.0/24 -j RETURN
Jan 03 10:15:45 k3s-node-1 k3s[1788]: I0103 10:15:45.918951    1788 iptables.go:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --rand
Jan 03 10:16:43 k3s-node-1 k3s[1788]: W0103 10:16:43.041905    1788 container_manager_linux.go:608] [ContainerManager] Failed to ensure state of "/systemd/system
lines 1-28/28 (END)

**Comment by alexgorbatchev** [comment]
Seeing the same thing with `v1.19.3+k3s3 (0e4fbfef)`

**Comment by 0rph3us** [comment]
I had the same problem with `v1.19.4+k3s1` and vagrant. eth0 is 10.0.2.15/24 on all machines and eth1 is 10.3.0.1XX/24. You can add the IPs from eth1 to start the server `/usr/local/bin/k3s server --node-external-ip 10.3.0.101 --node-ip 10.3.0.101`

**Comment by msabwat** [comment]
> -node-external-ip 10.3.0.101 --node-ip

Thank you, it worked for me !
Is the issue that k3s automatically picks the ip address on eth0 ? shouldn't it be documented somewhere ?

**Comment by brandond** [comment]
It's not eth0, the kubelet picks the interface with the default route. This is standard Kubernetes behavior.
