### ISSUE TITLE
Containerd and kubelet do not respect --data-dir

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#1358]
**Version:**
v1.17.2-alpha1+k3s1
```
K3S_TOKEN=xxx INSTALL_K3S_COMMIT=56b2f28d4f08ffe8ac3aff968934b4a8eb7a827c ./k3s.sh server --no-deploy=coredns,servicelb,traefik,local-storage --disable-cloud-controller --disable-network-policy --write-kubeconfig-mode=660
```

**Describe the bug**
* The state dir for the embedded containerd is hardcoded to /run/k3s/containerd.
* The root dir for kubelet is at /var/lib/kubelet on non-rootless configurations.

**To Reproduce**
* Install and use k3s
* Inspect /run/k8s and /var/lib/kubelet

**Expected behavior**
* containerd state dir is within the configured data directory.
* kubelet root dir is within the configured data directory.

**Actual behavior**
* The containerd state directory (including pod roots at /var/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/) do not respect the configured data directory. 
* The kubelet root dir is only nested within the data directory when k3s is run rootless.

**Additional context**
I would like the embedded containerd and kubelet to respect either the --data-dir option, or other options dedicated to this purpose. If you're trying to keep all k3s IO on a single disk (say, using SSD for k3s while the OS is on rotational disk or SD card in the case of rPi), the current state makes it difficult without juggling symlinks. Given, /run should be tmpfs, but I'm not sure if that's guaranteed on all distros.

https://github.com/rancher/k3s/blob/master/pkg/agent/config/config.go#L421
https://github.com/rancher/k3s/blob/master/pkg/agent/config/config.go#L433
https://github.com/rancher/k3s/blob/master/pkg/ctr/main.go#L38

**Comment by PPACI** [comment]
I came across this issue while doing some research for a rPi setup.

it appears that this is now addressed.
https://github.com/k3s-io/k3s/blob/master/pkg/agent/config/config.go#L375
https://github.com/k3s-io/k3s/blob/master/pkg/agent/config/config.go#L433

Do you see anything else ? Or could this issue considered solved ?

**Comment by brandond** [comment]
Data-dir only moves things that would normally go under /var/lib/rancher/k3s. The other stuff will probably have to stay the way it is for now, for compatibility reasons.

**Comment by PPACI** [comment]
My bad, indeed /var/lib/kubelet is still present and in use.

**Comment by ChristianCiach** [comment]
I think it is mildly surprising that K3s writes any files outside of its `data-dir`. We learned this the hard way, because our root file system is on a rather slow and small HDD. Instead, we have a large SSD partition mounted to `/ssd`, so I've configured K3s with `--data-dir /ssd/k3s`. Unfortunately, I didn't know that the Kubelet still uses another directory (`/var/lib/kubelet`) which quickly exhausted the root file system due to some large `emptyDir` volumes.

I could workaround this by moving the kubelet root directory into the k3s data dir, using the config file `/etc/rancher/k3s/config.yaml`:
```
kubelet-arg:
  - 'root-dir=/ssd/k3s/kubelet'
```
Still, I think this behavior is a bit surprising. I always had the assumption that K3s tries to present itself as a single, self-contained process to the user. The fact that the kubelet-process *bleeds* outside of the (otherwise self-contained) K3s data directory seems a bit strange, in my opinion.

**Comment by brandond** [comment]
Early versions of k3s did move the kubelet root dir into /var/lib/kubelet, but we encountered a fairly constant stream of problems with things (CNI/CSI plugins, monitoring daemonsets, etc) that would not support a relocated kubelet root dir.

**Comment by ChristianCiach** [comment]
Well, just to be sure, I could also create a symlink at `/var/lib/kubelet` to `{{ k3s_data_dir }}/kubelet`....

**Comment by ChristianCiach** [comment]
Even when moving the kubelet root-dir, these files will still be generated at `/var/lib/kubelet`:

```
# find /var/lib/kubelet/
/var/lib/kubelet/
/var/lib/kubelet/device-plugins
/var/lib/kubelet/device-plugins/kubelet.sock
/var/lib/kubelet/device-plugins/DEPRECATION
```
That's not an issue for me. Just an interesting observation.

**Comment by brandond** [comment]
Yep, that's one of the things that's essentially hardcoded.
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-deployment
