### ISSUE TITLE
More guidance on k3s ha with embedded db

### ISSUE THREAD

**Issue by rossbeazley** [k3s-io/k3s#1409]
I run a small mixed architecture cluster at home, armv7, armv8, x86_64. I tend to use raspberry pis for the master node and wanted to try a HA (embedded db) deployment as sometimes they just go pop.

At first I didn't realise its critical for an odd number of nodes, I understand this now.

After that I then had a cluster up but thought I should put a load balancer in front of the master nodes, or rather the API server I suppose. I was using haproxy in tcp mode to load balance across the three nodes on port 6443, eg;

# k3s HA Master
frontend f_k3s_ha_master_6443
	bind 192.168.10.1:6443
	mode tcp
	default_backend b_k3s_ha_master_6443

frontend http-internal
backend b_k3s_ha_master_6443
	mode tcp
	server pi2node02 192.168.10.191:6443
	server pi2node01 192.168.10.230:6443
	server pi3node01 192.168.10.224:6443

I have since stopped doing this as simple commands would fail, eg

$ kubectl get pods --all-namespaces -o wide
Error from server (ServiceUnavailable): the server is currently unable to handle the request

I have since replaced by kube config to point to the first master node i setup

So my question;

should I be load balancing across the master nodes as it seams with my setup everything hangs off of the first master.

thanks for your help with this, k3s is really awesome

**Comment by jacobblock** [comment]
+1, it seems like the masters make no use of K3S_URL (what I was specifying as lb) after initial configuration to get the set of master URLs. I didn't see this spelled out anywhere.

I was expecting the k3s.yaml server path to point to the lb, but I guess the masters need to know the state of every other masters in order to reach consensus, so it wouldn't make sense to have masters behind an LB except in the context of N agent nodes distributed across the masters.
