### ISSUE TITLE
Wireguard Setup

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#1608]
Hello, 

I have setup wireguard through `--flannel-backend=wireguard` 
Is there any way to first make sure all traffic is going through it ? 
And is there any way to add some specific configuration ? 
For example, adding a peer to the wireguard network that is not part of k3s ? Either to have a VPN to the cluster from personnal pc or to add ressource to the wireguard network ( for example an NFS server ) 

Regards

**Comment by alekc** [comment]
For the first point: on my setup i've closed flannel port 8472 on firewall leaving only the 51820 (wireguard port) exposed, and things are still working. 
Also, if you execute `wg` on one of the node you should be able to see all your nodes connected and the amount of traffic passwed between them. 

I am still investigating the second part of your enquiry, the lack of documentation on the subject is... frustrating.

**Comment by brandond** [comment]
You might post these questions in the flannel repo, as k3s is simply bundling it and generating the configuration file.

**Comment by adi90x** [comment]
Any update on how to use wireguard with k3s in an efficient way ?

**Comment by alekc** [comment]
@adi90x what do you mean by `an efficient way`?

**Comment by adi90x** [comment]
Hello,

I mean using Wireguard to secure network communication, either using it
straight from k3s ( --flannel-backend ) or using it from another
implementation ( squat/kilo ) ?
What is the recommended way ?
My setup is several host bare metal at home behind NAT ( so only with
private ip available ) , one that is in DMZ  so basically able to be joined
from web + NATed host, and some host in different cloud providers.
My question is how to deal with that , to have a efficient and secure
cluster ?

Regards,

**Comment by alekc** [comment]
The wireguard setup is not problematic (as long as it's installed on hosts before running k3s). In your case what can be tricky is the fact that you are half nat half not. Back in the day when I was setting up my cluster I had to develop a controller https://github.com/alekc-go/flannel-fixer to deal with the external IP and proper labelling.

Some (potentially) useful read topics about it
https://github.com/k3s-io/k3s/issues/1824
https://github.com/k3s-io/k3s/issues/2689
https://github.com/rancher/rancher/issues/22190
https://github.com/k3s-io/k3s/issues/50
https://github.com/rancher/k3os/issues/570

**Comment by Akay7** [comment]
Hi @adi90x 
In my case, I prefer to install Wireguard at the nodes and only on top of those nodes installing k3s without Wireguard since all traffic between nodes already encrypted.
Keep in mind that if your k3s installed with an external etcd cluster you should care about network encryption between etcd nodes.

**Comment by adi90x** [comment]
@Akay7 : Even worst , I am trying to implement HA etcd cluster ... Need to deal with etcd ip that annonce only internal ...

**Comment by adi90x** [comment]
@Akay7 : So you setup a wireguard network between nodes and then setup k3s using previously created wireguard interface ?

**Comment by Akay7** [comment]
> @Akay7 : So you setup a wireguard network between nodes and then setup k3s using previously created wireguard interface ?

Yes. 
For setup etcd I followed the [tutorial](https://github.com/hobby-kube/guide#etcd-setup).  And for k3s I use the next parameter: `--flannel-iface wg0`.

**Comment by paulwollgast** [comment]
Using the --flannel-iface flag has also worked for me to run k3s on top of wireguard, the respective --flannel-backend=wireguard flag was, for some reason, failing, also when combined with the face flag.

**Comment by msgeissler** [comment]
For me neither approach is really working.
I have a hosted server and two raspberry pis at home. If I use wireguard on the devices myself, I can connect them without any issues. However, if I start any agent with the `--flannel-iface wg0` option they lose their connection due to some kubernetes iptable changes. If I shut down the agent, the device gets its connection back.

With `--flannel-backend=wireguard` everything seems to work at first, but my nodes get their public ip / their local lan ip assigned as node ips. I am using the kubernetes dashboard which is trying to collect metrics from the nodes using the node ip, which does not work as these ips are running outside the wireguard connection.
Cert-manager is also not working in this case if it running on the nodes.
A small nginx sample deployment did work though, but overall this is not a usable setup.

Not sure how to solve this yet. Maybe I will try running the agents in docker and force it through wireguard running on the device (but I wanted to avoid wrapping it in docker just for that). Another solution could be to get k3s/flannel to use the ip the flannel wireguard interface as the node ip on startup. But I have absolutely no idea how to do that (yet).

**Comment by msgeissler** [comment]
I found out why `--flannel-iface wg0` was failing for me:
Using `AllowedIPs = 0.0.0.0/0` and `wg-quick up` does some `fwmark` magic in the background and gets caught by the kubernetes firewall iptables rules. Manually defining my wireguard network and the k3s CIDRs as `AllowedIPs` works with `wg-quick up`.

I still do have the cert-manager problems though:

> Internal error occurred: failed calling webhook "webhook.cert-manager.io": unexpected error when reading response body. Please retry. Original error: context deadline exceeded

**Comment by paulwollgast** [comment]
Great to hear!
Are you using the hostNetwork with your ingress controller? I've had cert-manager issues because the http-challenge could not be resolved as the lets-encrypt web hook did not reach the endpoint as Traefik was listening on the fireguard ip on port 80, switching out Traefik for NGINX helped as you can configure NGINX to use the hostNetwork, the webhook will then be forwarded accordingly which solved my problems. Here is the Helm Chart plus Config that I'm using:

`    chart: nginx-ingress-controller
    helm:
      parameters:
        - name: daemonset.useHostPort
          value: "true"
        - name: hostNetwork
          value: "true"
        - name: kind
          value: DaemonSet
        - name: replicaCount
          value: "1"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.5.0`

Maybe that helps, good luck!

**Comment by msgeissler** [comment]
Thanks for the suggestion @paulwollgast but my issue was actually with wireguard and one that I had fixed in the past but re-introduced again. A really stupid mistake. :man_facepalming:

I need a lower than usual MTU for the wireguard interface on my clients at home. Setting it to `1390` on my raspberrypis and just using `--flannel-iface wg0` works (`wg0` is my wireguard interface).

After that, I just had to fix some cert-manager configuration issues (I mixed ClusterIssuer and Issuer parameters, sadly the documentation switches between those for its examples) and, at least for now, my networking and k3s seem to work pretty well.

By the way I noticed that something was wrong with the networking when I deployed the kubernetes dashboard and if it was scheduled on one of my raspberrypies at home, it was not reachable via the `kubectl proxy` anymore. The proxy would return http connection problems or I would be able to get the index.html but the required css and js files would not load (long pending or 500 status in the browser network dev tools tab). My raspberrypis would also show dropped packages on their `wlan0` interface. After way too long it clicked in my head and I finally remembered the problems I had in the past and that I increased the MTU for some tests.

For now, running wireguard separately on the devices and using the wireguard interface for flannel seems to be working great now (haven't tested any heavy loads yet though). Using the public IP as `--node-external-ip` on the master-server ensures that it gets the correct external ip. On my worker nodes I am using the wireguard IP of my master-server for `--server https://xx.xx.xx.xx:6443`, this ensures they are using wireguard to connect to the server.

**Comment by Bessonov** [comment]
activity

**Comment by Bessonov** [comment]
Activity. But I'm not sure that it must be done in/with k3s.

**Comment by Bessonov** [comment]
Activity.

**Comment by brandond** [comment]
Possibly related:
* https://github.com/k3s-io/k3s/pull/6180

**Comment by liguobao** [comment]
This problem still exists
