### ISSUE TITLE
k3s on Android(arm or arm64)

### ISSUE THREAD

**Issue by seiyaa** [k3s-io/k3s#192]
run k3s on Android(arm64), and get the following tip:
> Failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"

lowmemorykiller is used for memory control on Android, cgroup memory is disable on Android

how can I run k3s on Android?
1.enable cgroup memory on Android?
2.remove the following code, and compile k3s?
```
if !strings.Contains(string(cgroups), "memory") {
    msg := "ailed to find memory cgroup, you may need to add "cgroup_memory=1 
    cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
    logrus.Error("F" + msg)
    return errors.New("f" + msg)
}
```
which is the better way?

**Comment by ibuildthecloud** [comment]
@seiyaa If we remove that check the pods will still fail to launch because they will try to use the memory cgroup.  We would have to patch across the board and remove and reference to memory.  I'd be interested if this is the only problem.  I believe there is another issue with the cpuset cgroup not having the `cpuset.` prefix in all the files.

**Comment by seiyaa** [comment]
@ibuildthecloud thanks
 `cat /proc/self/cgroup` on all my chhip boards(including hisilicon/mstar/mediatek), these boards have `cpuset`, but not have `memory`
I will try to add cgroup memory

**Comment by borg286** [comment]
Having memory limits for containers is very common when running kubernetes. Since this flag is part of the kernel, I think one would need to flash a modified Android OS that allows memory and CPU cgoups. Your debug message is geared towards raspberry pi devices. Is there an Android developer group that could point us to steps to get this enabled for Android. I'm fairly sure the support has been available for quite a while now.

**Comment by rjshrjndrn** [comment]
hey any progress on this ??

**Comment by yamlCase** [comment]
@dur3x @erikwilson @borg286 @seiyaa @kityun Looks like quite a few folks are interested in making k3s work on android (including myself).  Has anyone made progress getting it to run?  perhaps issue links to other projects?

**Comment by erikwilson** [comment]
In theory it should be possible for k3s to run on Android, since it is a Linux system. I think the caveat is that it probably will not, now or ever (without extensive changes), run on a stock system. To achieve this you will likely need a custom kernel with root access.

**Comment by brandond** [comment]
Closing due to age. Every time we've looked at Android it appears that (rooting issues aside) the kernel is missing critical features on most Android devices.

**Comment by morganchristiansson** [comment]
This is a challenge but not impossible.

https://wiki.postmarketos.org/wiki/File:K3s_cluster_built_with_hammerhead_and_docker.jpg

**Comment by MatrixManAtYrService** [comment]
The above link is to an image, but here's the associated writeup: https://wiki.postmarketos.org/wiki/User_talk:Docker
