### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by marcpar** [k3s-io/k3s#2419]
**Environmental Info:**
K3s Version: 

k3s version v1.18.9+k3s1 (630bebf9)

Node(s) CPU architecture, OS, and Version: 

Linux pi-4gb 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
Cluster Configuration:

1 master 1 worker
**Describe the bug:**

 ~/workspace/home-automation  kubectl logs bootcamp                                                                                                                                     10232  10:49:35 
standard_init_linux.go:211: exec user process caused "exec format error"

**Steps To Reproduce:**

- Installed K3s: 

then any deployment pod is not working 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by dweomer** [comment]
@marcpar how did you install k3s? The error you are reporting is indicative of attempting to execute a binary compiled for a different architecture.

**Comment by erikwilson** [comment]
I am guessing k3s is otherwise running fine, you can get nodes, describe pods, etc?

Please note you will get this error when running an amd64 container on an arm host. I am not sure if bootcamp publishes multi-arch images, but historically multi-arch has not been very well supported, so can be an issue for a lot of non-amd64 systems. It would be nice for us to give a different more significant error message, unfortunately I am not sure that is possible given the current state of docker images.
