### ISSUE TITLE
Change IP for 0.0.0.0:10250

### ISSUE THREAD

**Issue by pwFoo** [k3s-io/k3s#2489]
Hi,

I use k3s in a single node setup and try to move the 10250 port from 0.0.0.0 to an internal ip address.
How to adjust that?

Thanks!

**Comment by jerger** [comment]
Hi, found this is true for newest stable release. Why k3s is listening on 10250 instead listening on the given bind-adress?

**Comment by mac-chaffee** [comment]
The reason is that 10250 is the kubelet port. By default, kubelet binds to 0.0.0.0: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

In order to change that, you need to change that arg via either running `k3s server --kubelet-arg="address=<the_ip>"` or adding this line to `/etc/rancher/k3s/config.yaml`:

```
kubelet-arg:
  - "address=<the_ip>"
```
