### ISSUE TITLE
k3s cluster on master node with postgresDB failed to configure

### ISSUE THREAD

**Issue by sandhyarme** [k3s-io/k3s#2613]
Hi,

We followed below steps to setup k3s cluster with postgresDB as external datastore, but k3s failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod.

On Master node -
1. Check Postgres connectivity remotely 
psql --set=sslmode=disable -h <PostgresVM IP> -d postgres -U postgres -W
2. export K3S_DATASTORE_ENDPOINT='postgres://postgres:postgres@15.213.141.54:5432/postgres?sslmode=disable'
3. curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig=/home/centos/.kube/config --write-kubeconfig-mode=644 --disable traefik" sh -s - --docker

failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod 
Failed to create existing container
Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found.......................

Attached details k3s log.txt
[log.txt](https://github.com/k3s-io/k3s/files/5631581/log.txt)

**Comment by brandond** [comment]
Something appears to be wrong with docker's filesystem - you're missing both container filesystems and images that docker is expecting to be present.

```
Dec 03 00:38:09 kong.master k3s[25294]: E1203 00:38:09.018489   25294 manager.go:1123] Failed to create existing container: /kubepods/burstable/podda35d824-ce1f-4a43-8ae2-f37410dc343c/ea98c4ceca5426eb1811b404f2db92ebd0773967b909210ae0307c10952e449f: failed to identify the read-write layer ID for container "ea98c4ceca5426eb1811b404f2db92ebd0773967b909210ae0307c10952e449f". - open /var/lib/docker/image/overlay2/layerdb/mounts/ea98c4ceca5426eb1811b404f2db92ebd0773967b909210ae0307c10952e449f/mount-id: no such file or directory
Dec 03 00:38:09 kong.master k3s[25294]: E1203 00:38:09.019738   25294 manager.go:1123] Failed to create existing container: /kubepods/besteffort/podad5f799d-aa8e-42f8-8661-2c5ba4109d5b/808c8600c3d31d20a5e319653cc478a4055e4143090691d61d3173a529c101e6: failed to identify the read-write layer ID for container "808c8600c3d31d20a5e319653cc478a4055e4143090691d61d3173a529c101e6". - open /var/lib/docker/image/overlay2/layerdb/mounts/808c8600c3d31d20a5e319653cc478a4055e4143090691d61d3173a529c101e6/mount-id: no such file or directory
Dec 03 00:38:09 kong.master k3s[25294]: W1203 00:38:09.022412   25294 docker_sandbox.go:402] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "local-path-provisioner-6d59f47c7-jk52j_kube-system": unexpected command output Device "eth0" does not exist.
Dec 03 00:38:09 kong.master k3s[25294]: with error: exit status 1
Dec 03 00:38:09 kong.master k3s[25294]: W1203 00:38:09.026820   25294 docker_container.go:374] ignore error image "sha256:9d12f9848b99f4e5f5271b7cac02790de44ec12014762a83987cfff7f3c26106" not found while inspecting docker container "30785d0a1d1b5f87adfba89bb5a64878bfa94d9ea6a0462a6cb817dee1e8f315": no such image: "sha256:9d12f9848b99f4e5f5271b7cac02790de44ec12014762a83987cfff7f3c26106"
Dec 03 00:38:09 kong.master dockerd[1527]: time="2020-12-03T00:38:09.027813806+05:30" level=error msg="Handler for GET /v1.38/containers/4e78ac5f3b079228f7e527b1e5933aa4868b6a03d6ad8dfe5b9e27408fdb5903/json returned error: stat /var/lib/docker/overlay2/1126b626343961feb2383796fc191b6ca9f7b1e7959cd11b6cae226a40dd0d89: no such file or directory"
Dec 03 00:38:09 kong.master k3s[25294]: E1203 00:38:09.028568   25294 remote_runtime.go:329] ContainerStatus "4e78ac5f3b079228f7e527b1e5933aa4868b6a03d6ad8dfe5b9e27408fdb5903" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: stat /var/lib/docker/overlay2/1126b626343961feb2383796fc191b6ca9f7b1e7959cd11b6cae226a40dd0d89: no such file or directory
Dec 03 00:38:09 kong.master k3s[25294]: E1203 00:38:09.028603   25294 kuberuntime_manager.go:966] getPodContainerStatuses for pod "local-path-provisioner-6d59f47c7-jk52j_kube-system(3034f003-a357-4c13-932d-0420388e9fa7)" failed: rpc error: code = Unknown desc = Error response from daemon: stat /var/lib/docker/overlay2/1126b626343961feb2383796fc191b6ca9f7b1e7959cd11b6cae226a40dd0d89: no such file or directory
```

What sort of filesystem is this hosted on? Did you run out of disk space? Did someone delete files from /var/lib/docker?

**Comment by sandhyarme** [comment]
Hi Brandond,

Thanks for the response.

We have tried below steps on new centos 7 VM.
- https://rancher.com/docs/k3s/latest/en/advanced/#using-docker-as-the-container-runtime
- export K3S_DATASTORE_ENDPOINT='postgres://postgres:postgres@15.213.141.54:5432/postgres?sslmode=disable'
-  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig=/home/centos/.kube/config --write-kubeconfig-mode=644 --disable traefik" sh -s - --docker

We are facing below error..
"Cluster-Http-Server 2020/12/05 00:50:30 http: TLS handshake error from 127.0.0.1:53886: remote error: tls: bad certificate"

and 
failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "ingress-kong-6dcc89b79b-x27rb_kong"

But why "ingress-kong "  is here we are installing basic k3s cluster.. ?
Attached detailed log for reference.
[log.txt](https://github.com/k3s-io/k3s/files/5645032/log.txt)

**Comment by brandond** [comment]
I'm guessing you're reusing a database from a previous install? Are you dropping the database and running k3s-uninstall.sh between attempts to clean up both the database AND the nodes?

**Comment by sandhyarme** [comment]
Hi Brandond,

Have deleted all databases, installed freshly still receiving below errors.
Cluster-Http-Server 2020/12/08 18:05:59 http: TLS handshake error from 15.213.141.59:48848: remote error: tls: bad certificate
Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
Failed to update node kong.master: Put \"https://127.0.0.1:6443/api/v1/nodes/kong.master\"

[log.txt](https://github.com/k3s-io/k3s/files/5659321/log.txt)

**Comment by brandond** [comment]
What OS is this on? Could possibly be a duplicate of #2548

**Comment by dotkrnl** [comment]
I am having a similar issue where I use CockroachDB as the HA PostgresDB backend.  The distributed DB is much slower than a local one.  In my understanding and from the logs, it seems like that while the k3s server is still creating the proper authorization, the agent is already trying to use those.  Therefore, it causes errors to be sent to SystemD and terminating the whole k3s.  In this case, this is a duplicate of #2548 while still reproducible now.

I am attempting to run k3s-server `--disable-agent` and it is still having some troubles like:

`time="2021-02-06T03:42:15.857797594+08:00" level=fatal msg="failed to start controllers: timed out waiting for the condition"`

I am waiting to see if the condition can eventually converge with `--disable-agent`.

**Comment by brandond** [comment]
@dotkrnl Running with --disable-agent is a bad idea as you won't even see the node in the cluster. If you're getting things timing out, it's most likely due to the database not responding quickly enough.

There have been other issues with CockroachDB, see k3s.io/kine#74

**Comment by dotkrnl** [comment]
@brandond Thank you so much!  Although my question is now diverge from this thread before I creating another issue I would like to see if there is anything I am missing.  Now I use `--disable-agent` to work around a problem that is similar to #2548 (though I am not sure if it is just filtering out some noise in the logs because I do not have a working setup to experiment yet).  However, even if use a faster database setup and there is no timeout related to the DB in the logs now and all requests are in tens to hundreds of ms, the problem persists.  I find that the `timed out` of controller setup seems to be due to this -- it repeatedly appear till the very end of the log.

```
E0206 17:23:20.119514       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope
```

My setup is a fresh CockroachDB with one fresh master node on a physical machine, and another fresh master node on Docker on another machine, they can communicate with each other's IP, and the `--node-ip` and `--advertise-address` are set.  The only other options are `--datastore-endpoint` and `--disable-agent`.  Both of them are failing due to the same reason.

I have been struggling for days.  Any help is appreciated!

**Comment by brandond** [comment]
@dotkrnl it is expected that you will see a lot of warnings and errors during the initial startup as controllers come up and configure the cluster for the first time. Some things need to wait for other things to be ready, and will retry while logging errors until that occurs.

Can you post the k3s logs from both nodes, starting with a clean install? If you can try without any arguments except the datastore endpoint, that would rule out any accidental misconfiguration.

**Comment by dotkrnl** [comment]
@brandond

[Here is the complete v=10 logs from the Docker instance](https://gist.github.com/dotkrnl/42a0f82904d194431da6dd3b8c7d6cc1) and [the default level logs](https://gist.github.com/dotkrnl/aa43ee89f838b10b86d3b69dc4cf2d84) with `server --datastore-endpoint='[reacted]' -v 10` or no `-v 10`, both DB and k3s are clean installations.  The image used is `rancher/k3s:v1.20.2-k3s1` with `k3s-server:/var/lib/rancher/k3s` mounted and `/run` and `/var/run` as tmpfs as the documentation required.  The container is privileged.

```
# almost the same as https://github.com/k3s-io/k3s/blob/master/docker-compose.yml
k3s-server:
  image: "rancher/k3s:v1.20.2-k3s1"
  command: "server --datastore-endpoint='[redacted]'"
  volumes:
    - k3s-server:/var/lib/rancher/k3s
  tmpfs: [/run, /var/run]
  privileged: true
```

And [here is the complete v=10 logs from the physical machine installation](https://gist.github.com/dotkrnl/94d6b6e086eccf8c63b6295819618bdf) and [the default level logs](https://gist.github.com/dotkrnl/f199b20005957d24358ddafba716193f) with `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.2+k3s1 sh -s - server --datastore-endpoint='[reacted]' -v 10` or no `-v 10`, on CentOS 7.  Both DB and k3s are clean installations too.

Those `--v=10` logs are large so you may want to check them with these direct links:

```bash
# docker --v10
curl https://gist.githubusercontent.com/dotkrnl/42a0f82904d194431da6dd3b8c7d6cc1/raw/1b705d1a0ce42175fbd95d9fcb105613f5b82559/k3s-docker-v10.log | less -r
# docker default
curl https://gist.githubusercontent.com/dotkrnl/aa43ee89f838b10b86d3b69dc4cf2d84/raw/9845570f98f4cc6a7af6479844e9b98e0be7e8de/k3s-docker-default.log | less -r
# physical --v10
curl https://gist.githubusercontent.com/dotkrnl/94d6b6e086eccf8c63b6295819618bdf/raw/b49803b3498e06a4ed35ea4ce1dc21c4f33533da/k3s-physical-v10.log | less -r
# physical default
curl https://gist.githubusercontent.com/dotkrnl/f199b20005957d24358ddafba716193f/raw/72c8497841a2bfda85f0274a96de2a2d8ed52d56/k3s-physical-default.log | less -r
```

Both setups work properly without `--datastore-endpoint` and both servers should have sufficient hardware resources.  Besides, I tried manually create cluster role binding to `system:masters` for the failing roles but it does not help.  Please let me know if you need another verbose level.  If this issue is non-trivial and not related to the thread, I will create another issue if more proper.

Thank you so much!

**Comment by brandond** [comment]
-v=10 is probably excessive. K3s itself doesn't use klog levels, but does have a --debug flag that is fairly useful. I'll take a look at those logs later.

**Comment by dotkrnl** [comment]
@brandond Thanks.  My setup is several physical hosts with some of them already have Docker workloads deployed.  Therefore I use Zerotier to create another layer of network so that the physical hosts and the containers are like in the same network so basically it should have no difference from a host network mode and I confirmed that they can communicate with each other with no problem.  I did try to use a containerized-only cluster (the previous docker's log is this case) and it does not work either.

However, if the container is a problem, I just did another experiment on __a host-only local-network environment__ and here is a log from a host-network-only configuration using only the `--debug` flag and `--datastore-endpoint`:  [node1 (n100)](https://gist.github.com/dotkrnl/89a4aa7dc314a3a623a0c30bc0374215) and [node2 (n101)](https://gist.github.com/dotkrnl/0e12676320d96cb17b96420a828dd41b).  The three DB nodes and the two nodes are in the same 10Gbps local network (ping is ~ms, not Zerotier anymore).  They are all clean installation but it is still failing.  I let them restart automatically for 15 mins so this time they are logs for multiple runs since the initial run.  You can search for `fatal` to see the errors (RBAC almost every time). (6:01:3xPM to )...

```bash
curl https://gist.githubusercontent.com/dotkrnl/89a4aa7dc314a3a623a0c30bc0374215/raw/ce2b107f30d379a7d7f819d5c0fa4590ec8fb7e7/k3s-debug-n100.log | less -r
curl https://gist.githubusercontent.com/dotkrnl/0e12676320d96cb17b96420a828dd41b/raw/8472a59480cf8de8a6290dfc906e7602b97fc5a8/k3s-debug-n101.log | less -r
```

**Comment by iwilltry42** [comment]
> Just to level set, I'm not sure I've seen anyone try to create a mixed host and containerized cluster. @iwilltry42 may have some suggestions since he works quite a bit with containerized k3s for k3d. Have you tried running it in host network mode?

Thanks for the ping. Seems like I was a bit late here. Cool that you got it solved @dotkrnl and that it apparently wasn't due to the docker environment :+1:

**Comment by brandond** [comment]
CockroachDB isn't technically supported at the moment but if we do QA it that's great information to have!
