### ISSUE TITLE
Documentation on node token lifetime and scope?

### ISSUE THREAD

**Issue by Michaelhobo** [k3s-io/k3s#2645]
I have a couple questions about the security of the node token, which I had trouble finding in docs:

- What's the scope of the node token? Is it only used to allow an agent to initially join a server's cluster?
- What's the lifetime of the node token, does it have a TTL? If we rotate the node token, will agents have trouble connecting?
- If we're worried about the node token being compromised, and if it's an actual problem (based on answers to previous 2 questions), is there something else that we could do?

**Comment by brandond** [comment]
* The node token is used by both servers and agents to join the cluster. It does not have any access to the kubernetes API itself, but does have access to k3s-specific endpoints that are used to bootstrap certificates and other data necessary to join the cluster
* It is a static password that is used to authenticate to the server using the Basic authentication scheme. It does not expire.
* Token rotation is not well supported at the moment, as it is also used to encrypt bootstrap data at-rest within the datastore, and changing the token will prevent the data from being decrypted. You might consider setting the [--agent-token](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#experimental-options) option, which can be rotated without affecting other things.
* Are you worried about what happens IF the token is compromised, or are you trying to decide what to do with a token that HAS been compromised?

**Comment by Michaelhobo** [comment]
> Are you worried about what happens IF the token is compromised, or are you trying to decide what to do with a token that HAS been compromised?

I'm looking into IF the token is compromised. I'm evaluating adopting k3s for my team, and if the only auth mechanisms for nodes joining servers is to share a static non-rotatable password with all nodes, I think that's a blocker for my team. 

> It is a static password that is used to authenticate to the server using the *Basic authentication* scheme. It does not expire.

It sound like there's another auth scheme that not the *Basic authentication* scheme?

**Comment by brandond** [comment]
> It sound like there's another auth scheme that not the _Basic authentication_ scheme?

Not for bootstrapping nodes, no. We use basic auth over HTTPS for the initial bootstrap request. Afterwards, once the nodes have provisioned certificates, everything uses TLS mutual authentication (client + server certificates).

**Comment by Michaelhobo** [comment]
> > if the only auth mechanisms for nodes joining servers is to share a static non-rotatable password with all nodes, I think that's a blocker for my team.
> 
> Most users appreciate this, as it allows them to check the join token in to their secrete management tool (Ansible Vault, Parameter Store, etc) and then provision additional nodes without having to worry about the token expiring. At some point, you have to embed credentials somewhere. Whether this is an API token, client certificate, passphrase, etc doesn't make a huge difference - you still have a secret to protect.

I think the bigger problem is that it's a globally shared credential. If each node had an identifying credential (e.g. a signed JWS) that tied it to an identity, if that node is compromised, you can at least revoke it permissions. But with the current auth scheme, if one node is compromised, and the key is leaked, it's a lot harder to revoke permissions for a single node, or to blacklist a single node. I think this is even more important for edge/IoT devices, where physical access compromise might be a lot more prevalent.

**Comment by brandond** [comment]
At some point we will probably support something along the lines of [kubeadm's bootstrap tokens](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/). I don't have a roadmap date for that though.

**Comment by chris13524** [comment]
This limitation is also something my team is trying to overcome.

I believe k3s users can override the entire default authentication functionality using `--kube-apiserver-arg` and `--kubelet-arg` to provide custom certificates and even use `--bootstrap-kubeconfig` (and a different `--kubeconfig` as well) in the kubelet for supporting bootstrap tokens? So while k3s would still be trying to manage certificates, we could make this no-op and control the certificates and authentication ourselves.

**Comment by chris13524** [comment]
This limitation is also something I am encountering.

I believe k3s users can override the entire token authentication functionality using `--kube-apiserver-arg` and `--kubelet-arg` to provide custom certificates and even use `--bootstrap-kubeconfig` (and a different `--kubeconfig` as well) in the kubelet for supporting bootstrap tokens? So while k3s would still be trying to manage certificates, we could make this no-op and control the certificates and authentication ourselves.

**Comment by brandond** [comment]
Yes there are a couple different ways you could hack around the current CA/kubelet bootstrap logic, but at that point you've redone a bunch of the value that k3s itself provides.

**Comment by chris13524** [comment]
I'll note for @Michaelhobo that regular Kubernetes doesn't support for revoking a worker node's access to the control plane. It doesn't support certificate revocation so you'd have to not renew the certificate and wait for it to expire. I guess with the current state of things, k3s isn't really out of line.

**Comment by brandond** [comment]
Kubernetes does not in general have a great 'hostile node' story. If someone has access to one of your control-plane or datastore nodes, you should basically treat the entire cluster as compromised. Just rotating the join token and rebuilding the node does NOT get you anything. Having an compromised agent (kubelet) isn't great either since the kubelet has access to secrets and such.

**Comment by chris13524** [comment]
I have been referring specifically to agent compromise. Agreed re: server node compromise. Worker nodes in IoT situations have the risk of physical attack and also run more dynamic/less trusted workloads and thus have most risk for compromise.

If a worker node is compromised, there are other security features such as `NodeRestriction` that ensure the kubelet is only able to access resources that has been scheduled to it. Then you can have other application-level functionality for detecting and mitigating malicious behavior

**Comment by Michaelhobo** [comment]
> I'll note for @Michaelhobo that regular Kubernetes doesn't support for revoking a worker node's access to the control plane. It doesn't support certificate revocation so you'd have to not renew the certificate and wait for it to expire. I guess with the current state of things, k3s isn't really out of line.

@chris13524 That doesn't sound great either, I didn't know that. Thanks for pointing that out. I still think k3s's security story is way worse than k8s. With k8s, if you can strengthen the security of handing out bootstrap tokens, at least you can guard against bad nodes joining in the first place. But, k3s tokens are long-lived and often stored in plain text on the worker nodes (e.g. https://get.k3s.io will write the token to systemd RC files). With my project, physical access is also one of the big problems, and it really surprised me that a project that claims it's great for IoT has a security problem that makes it least secure on IoT applications.

**Comment by brandond** [comment]
Note that our typical IoT deployment story sees a complete K3s cluster at each edge location, centrally managed by tools like Rancher and Fleet. This is possible because a single K3s node is capable of running all components in a lightweight footprint. In this case the security boundary is the cluster as a whole - the posture of any individual node within the cluster is assumed to be equal, regardless of whether it's a server or an agent.

**Comment by liyimeng** [comment]
@brandond I think this need to take into serious consideration. If to use k3s in production, we expect cluster long living for a while, but not tear down and set up a in  daily base.

**Comment by brandond** [comment]
Reopening for #6663

**Comment by dereknola** [comment]
Closed again as https://github.com/k3s-io/docs/pull/101 has addressed new questions.
