### ISSUE TITLE
core DNS using only the first nameserver entry in /etc/resolv.conf

### ISSUE THREAD

**Issue by Mixie-12** [k3s-io/k3s#2659]
**Environmental Info:**
K3s Version: k3s version v1.19.4+k3s1 (2532c10f)

Node(s) CPU architecture, OS, and Version: 
Linux uh-iaas-bgo-sysnordic-k3s-worker-1 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

2 masters, 1 workers

**Describe the bug:**

coredns only uses the first DNS entry in /etc/resolv.conf

**Steps To Reproduce:**

1. Modify /etc/resolv.conf to have multible nameservers
2. Install K3s
3. Run

**Expected behavior:**

coredns to use both nameservers

**Actual behavior:**

coredns only uses the first nameserver

**Additional context / logs:**

By using the default dns policy, it looks like dns works correctly on all nodes;
kubectl run -i --restart=Never --rm test-${RANDOM} --image=ubuntu --overrides='{"kind":"Pod", "apiVersion":"v1", "spec": {"dnsPolicy":"Default"}}' -- sh -c 'cat /etc/resolv.conf'

**Comment by brandond** [comment]
Is this an issue with k3s, or coredns?

**Comment by Mixie-12** [comment]
Not sure if the issue is in coredns, or k3s deployment of it

**Comment by brandond** [comment]
What makes you suspect it's only using one nameserver?

**Comment by Mixie-12** [comment]
Here is an example:

I use a custom DNS server so I can get load balancing for the master nodes.
I change the /etc/resolv.conf, and get the following config;
![image](https://user-images.githubusercontent.com/43768459/101540247-06689580-39a0-11eb-8ba5-6be6dac0f47c.png)
Then I test the DNS, 
![image](https://user-images.githubusercontent.com/43768459/101540480-5d6e6a80-39a0-11eb-9ac0-084e2f435d99.png)
And success, the worker node can reach the master using the custom DNS name
But if i try to look up google i get:
![image](https://user-images.githubusercontent.com/43768459/101540994-0fa63200-39a1-11eb-838e-796da45a0269.png)
I tried switching the DNS arround using the following config;
![image](https://user-images.githubusercontent.com/43768459/101540183-ee911180-399f-11eb-805b-8c2425de6bd5.png)
Then I redeployed  coredns with; kubectl get pods -n kube-system -oname |grep coredns |xargs kubectl delete -n kube-system

And now I could reach google, but not my custom DNS server

**Comment by Mixie-12** [comment]
Trying to use following workaround with no luck;
https://medium.com/@rishasi/custom-dns-configuration-with-coredns-aks-kubernetes-599ecfb46b94

**Comment by brandond** [comment]
So your custom DNS server won't resolve google.com because it's not configured to serve non-authoritative lookups for clients in your cluster. Google DNS of course won't resolve your custom DNS zone. You're trying to work around this by listing both servers - but that's not how clients work because NXDOMAIN is not an error that will cause it to try the other DNS server. It doesn't just keep trying servers until one of them works; it will only try another one if it gets no response, or an actual error response.

The fix for this would be to do one of the following:
1. Configure your custom DNS server to allow nonauthoritative requests from your cluster nodes, and use this as your upstream DNS server. 
  You might not want to do this if your intent is for it to only be an authoritative server and not serve requests for other domains.
2. Configure CoreDNS to send requests for `cluster.no` to your custom DNS server by adding a line to your coredns configmap: `forward .cluster.no 158.39.77.251`
  This is a little more complicated due to the fact that you will have to copy the coredns manifest at `/var/lib/rancher/k3s/server/manifests/coredns.yaml` to another file in that directory before modifying it, and then `--disable coredns` and restart k3s. This is to prevent k3s from reverting your changes on restart.

**Comment by Mixie-12** [comment]
Thanks, it worked!
Here is an instruction for future travelers;

1. Save config -----
`cat /var/lib/rancher/k3s/server/manifests/coredns.yaml > coredns.yaml`

2. Change config to look somthing like this;
```

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    domain-name:53 {
        errors 
        cache 30
        forward . custom-dns-server
        reload
    }

```
Replace domain-name with your domain name. 
Replace custom-dns-server with your custom DNS server IP address.


3. Run config

`kubectl apply -f coredns.yaml`

4. Restart k3s dns

`kubectl delete pods -n kube-system -l k8s-app=kube-dns`

5. Verify DNS is correct 

```
kubectl run busybox --restart=Never --image=busybox:1.28 -- sleep 3600
kubectl exec busybox -- nslookup www.google.com
```
