### ISSUE TITLE
Are --secrets-encryption going to be graduated from experimental state to stable?

### ISSUE THREAD

**Issue by brlbil** [k3s-io/k3s#2660]
Hi,

We are planning to use `--secrets-encryption` option for production, but this future is marked as experimental. So we are hesitant to use it.  I would really appreciate if we can get some answers to our question regarding this future.

* What are the plans for this future?
* Is there a timeline?
* Could it change or be removed in the future?

Regards

**Comment by brandond** [comment]
The `secrets-encryption` flag is marked as experimental because it has not seen as much use or feedback as other features. We have no plans to remove it, and there are no known issues with the current implementation, but it may not be as polished as we would like.

It is really just a shortcut for configuring upstream encrypted secrets function using the AESCBC provider with a randomly-generated static key:
- https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers
- https://github.com/k3s-io/k3s/blob/v1.20.2+k3s1/pkg/daemons/control/server.go#L1073

Note that the random key is generated on-demand and not synchronized across servers in a HA cluster; this is something that we would probably handle before removing the 'experimental' flag from the feature. Until then, if you want to use the feature on a HA cluster, you will need to manually synchronize or generate the contents of the secrets encryption configuration file at `/var/lib/rancher/k3s/server/cred/encryption-config.json` across servers before enabling it.

**Comment by brandond** [comment]
Actually, I take back that last note. We did in fact add code to synchronize the encryption configuration across nodes. It is stored in the datastore as part of the bootstrap data that includes the cluster CA certificates, which is itself encrypted at rest using the join token as the encryption passphrase.

**Comment by brlbil** [comment]
Which version forward is the code to synchronize the encryption configuration available? I have looked around but I am afraid I am not familiar with the code base and lost a little bit.

**Comment by brandond** [comment]
It was added in our v1.17 release, which is now end of support as per upstream's release lifecycle. It is available in all currently supported release branches.

**Comment by brlbil** [comment]
Great I have tried and it seems to work even with a multi-master setup.
I hope this future can be graduated as stable soon.
I think I got the answers I need so we can close this ticket.
Thank you for all the help.
