### ISSUE TITLE
Shared Storage

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#2742]
Hello,

Is there any project like k3s, to enable shared storage ?
I am looking for something "easy" to setup, in terms of setup I have several node , some on cloud , some on premise ( behind a NAT ).
At the moment, I am using an NFS server to provide persistent storage, however this NFS server is behind the NAT and thus only available from nodes that are also behind it.
Node on the cloud therefore don't have any persistent storage.

Is there any project (maybe side project to k3s) to create an easy shared filesystem between all host ? 
I am also looking to connect my NFS Server through a vpn inside the cluster but I didn't succeed at the moment .

Regards,

**Comment by brandond** [comment]
There are multiple options in the distributed storage space (Longhorn, OpenEBS, etc) but none of them are going to perform particularly well on a dispersed cluster since they generally rely on low-latency, high-bandwidth links between nodes.

**Comment by doug62** [comment]
@adi90x May I ask how you got NFS working with K3s?  I'm running on windows inside docker-compose... (thanks)

**Comment by adi90x** [comment]
Hello @doug62 , 
Not sure if it will work with Windows , but on linux I use nfs-client-provisioner helm chart to connect to my local NAS .
@brandond : I am now trying Longhorn , only missing feature at least for development purpose is the easy access to saved data ( i.e : at the moment, I can mount the same NFS share on my laptop and change everything :) , anyway thanks for the information

**Comment by doug62** [comment]
Re: Windows K3s Docker-Compose - I'm afraid that it is not possible to use NFS within the docker stock images because K3S doesn't install 'nfs-utils', (neither does stock K8) i was unable to ssh into the container and install it but found that this guy ( https://github.com/sjmiller609/baremetal_kube/blob/3829589ab2b7747389f7f281fd1d246f851c0697/roles/container-linux-setup-for-k3s/files/Dockerfile#L1-L36 ) illustrated a way to rebuild the images however this is out of date.  About to research a dedicated NFS image to attach to an internal volume and share that with K3s.  Thoughts/Advice most welcome.

**Comment by doug62** [comment]
@adi90x Re VPN: OpenVPN is the industry standard linux VPN, there are several images, you can create a network within a docker-compose.

**Comment by adi90x** [comment]
@doug62  : in Linux your host need to be able to access nfs, maybe you need to check how windows can access it first.
Yes  I will probably end up creating a wireguard network before launching k3s , would have been great to have it included in k3s... Having the availability to create a full mesh encrypted network on startup .

**Comment by doug62** [comment]
@adi90x Since I am running K3s in docker/compose images on windows, and since Windows/Docker can't mount Shared volumes, I will need to modify the K3s image to somehow mount SMB/NFS volumes, filed a bug here: @2757
