### ISSUE TITLE
Master node IP token over by worker while kube-proxy running in ipvs mode and traefik running

### ISSUE THREAD

**Issue by paxnil** [k3s-io/k3s#2804]
**Environmental Info:**
K3s Version: 

k3s version v1.19.5+k3s1 (b11612e2)

Node(s) CPU architecture, OS, and Version: 

Linux k3s204 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master, 1 worker

**Describe the bug:**

Master node IP token over by worker while kube-proxy running in ipvs mode and traefik running.

**Steps To Reproduce:**

- Installed K3s on master: 
```
# cat /etc/rancher/k3s/config.yaml
cluster-cidr: 172.31.128.0/17
service-cidr: 172.31.0.0/17
cluster-dns: 172.31.0.10
flannel-backend: host-gw
kube-proxy-arg:
- proxy-mode=ipvs
# curl -sfL https://get.k3s.io | sh -
```
- Installed K3s on worker:
```
# cat /etc/rancher/k3s/config.yaml
kube-proxy-arg:
- proxy-mode=ipvs
# curl -sfL https://get.k3s.io | sh -
```

**Expected behavior:**

Master node should be reachable after worker joined cluster.

**Actual behavior:**

Master node's IP address was token over by worker unless traefik disabled

**Additional context / logs:**

`ip addr` shows that node ip (172.20.20.204) were also bound to kube-ipvs0 on both nodes
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:86:4f:b2 brd ff:ff:ff:ff:ff:ff
    inet 172.20.20.204/23 brd 172.20.21.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe86:4fb2/64 scope link
       valid_lft forever preferred_lft forever
3: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 0a:19:64:e0:f8:fc brd ff:ff:ff:ff:ff:ff
    inet 172.31.0.10/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.31.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.31.7.79/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.31.27.94/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.31.77.16/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.20.20.204/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
```

**Comment by brandond** [comment]
We don't make any modifications to the kubelet IPVS code, so I suspect that whatever is going on, it's not K3s specific. It may be an odd interaction with ServiceLB, where IPVS for some reason wants to advertise the Kubernetes Service IP address from both nodes, and due to how ServiceLB works, that is the actual IP address of one of your nodes.

**Comment by comphilip** [comment]
@brandond You are right. IPVS mode is not supported yet due to ServiceLB implementation.

**Comment by comphilip** [comment]
@brandond @paxnil  Finally I found the solution. 

1. ServiceLB Controller uses nodes' IPs as load balance service external IP list, 
1. Then these external IP list will bind to `kube-ipvs0` interface by kube-proxy in IPVS mode.
1. Then worker cannot connect to master node.

So just make ServiceLB not to use nodes' IPs as load balance service external IP list. By default, K3S node has only internal type IP, no external type IP defined. In ServiceLB controller, service external IP list is collected in this way:
https://github.com/k3s-io/k3s/blob/02a5bee62f5d7a0811a6a9401fc9ff5b1399c0bc/pkg/servicelb/controller.go#L215-L217

So just add a external IP to a node, the IP doesn't need to existed. I choose 100.64.0.1(carrier-grade NAT), it is not used in private LAN and public Internet. Luckly, servicelb does not use external IP at all. So change external IP to a non-existed IP has no harm to load balance.

Change one worker node `k3s agent` to `k3s agent  --node-external-ip 100.64.0.1 --kube-proxy-arg proxy-mode=ipvs`. It will switch to IPVS mode and works well.

**DO NOT add external ip to master node, worker node will use the external IP to connect to master and it will failed.**

Change master node `k3s server` to `k3s server --kube-proxy-arg proxy-mode=ipvs` to make master swtich to IPVS.

**Comment by comphilip** [comment]
@paxnil 

Previous workaround has side effect: NodePort and Load Balancer service with `externalTrafficPolicy=Local` cannot get correct client IP, but NATed IP (IP of `cni0` network interface)

Kube-Proxy uses external IP list of service to setup ipset to filter out which network traffic does not need SNAT and forward them to local pod. If cheating with 100.64.0.1,  ipset rule cannot match the external traffic and will fallback behavior of externalTrafficPolicy=Cluster, which source ip is NATed.

It it better to follow Kube-Proxy's design way. 

Since my testing cluster is in the same LAN network, So I can assign extra another LAN IPs as internal IPs to nodes. Nodes can communicate each other with these internal IPs and existed IPs acts as external IP. No extra network interface is needed, a NIC can be assigned many IPs.

## Example
### Master
External IP/Existed IP: 192.168.10.2
Internal IP: 192.168.11.2
K3S command: `k3s server --node-ip 192.168.11.2 --kube-proxy-arg proxy-mode=ipvs`

### Worker
External IP/Existed IP: 192.168.10.3
Internal IP: 192.168.11.3
K3S command: `k3s agent  --node-external-ip 192.168.10.3 --node-ip 192.168.11.3 --kube-proxy-arg proxy-mode=ipvs`
