### ISSUE TITLE
Install.sh fails when using wget

### ISSUE THREAD

**Issue by nir2292** [k3s-io/k3s#2814]
We're installing k3s on an ARM64 device that doesn't have curl installed.
Downloading and running `install.sh` from https://get.k3s.io gives
```
[INFO]  Finding release for channel latest
https://update.k3s.io/v1-release/channels/latest
[INFO]  Using v1.20.0+k3s2
socket-worker-5029ae85.js as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.0+k3s2
socket-worker-5029ae85.js/sha256sum-arm64.txt
[ERROR]  download needs exactly 2 arguments
```
tracing this to here:
https://github.com/k3s-io/k3s/blob/1d4adb0301b9a63ceec8cabb11b309e061f43d5f/install.sh#L355
and reproducing the behavior by running
`echo $(wget -SqO /dev/null ${version_url} 2>&1 | grep -i Location | sed -e 's|.*/||')`
which outputs
`v1.20.0+k3s2 socket-worker-5029ae85.js`

the desired output is `v1.20.0+k3s2`

I'll add that installing curl and running `curl -sfL https://get.k3s.io | sh -` works perfectly.

**Comment by brandond** [comment]
What version of wget do you have? Is it actual wget, or busybox's fake wget?

**Comment by nir2292** [comment]
GNU Wget 1.19.4

**Comment by arron-f** [comment]
The problem is combination of the script and likely github changed policy.

I also have same issue... its because the script does insensitive grep. There is a "online.visualstudio.com/api/v1/locations" now in the Content-Security-Policy. Removing the '-i' fixes the problem, since Location is a https://tools.ietf.org/html/rfc7231 pg 68 compliant thingy it should always be a capital anyway.

$ wget -SqO /dev/null https://update.k3s.io/v1-release/channels/stable 2>&1 | grep -i Location
  Location: https://github.com/k3s-io/k3s/releases/tag/v1.20.0+k3s2
  Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com online.visualstudio.com/api/v1/locations; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker-5029ae85.js gist.github.com/socket-worker-5029ae85.js

**Comment by brandond** [comment]
In #1751 we actually had an issue with the Location header being lower-case. According to RFC they are case-insensitive, and http2 actually folds everything to lowercase so it's not really safe to assume either.

**Comment by kaharlichenko** [comment]
The issue is still valid. Got the same error while installing on Alpine Linux using their "virtual" image flavor.

There's no `curl` preinstalled and `wget` happens to be provided by BusyBox.
