### ISSUE TITLE
Release channels and upgrades

### ISSUE THREAD

**Issue by aureq** [k3s-io/k3s#2820]
**Environmental Info:**
K3s Version: 
k3s version v1.19.4+k3s1 (2532c10f)

Node(s) CPU architecture, OS, and Version: 
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Linux jupiter 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

Cluster Configuration:
Single node configuration.

**Describe the bug:**
Following the [k3s release page](https://github.com/k3s-io/k3s/releases), I noticed `v1.19.7+k3s1` is the `latest release` showing in green and `v1.20.2+k3s1` is marked as a pre-release showing in orange.

I just tried to upgrade my single node cluster to the latest v1.19.x using the following command : `curl -sfL https://get.k3s.io  | INSTALL_K3S_EXEC="--disable traefik" sh -`. However, version `v1.20.0+k3s2` was pulled for some reasons.

```
# curl -sfL https://get.k3s.io  | INSTALL_K3S_EXEC="--disable traefik" sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.20.0+k3s2 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.0+k3s2/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.20.0+k3s2/k3s
(I pressed CTRL+C before the download completed to interrupt the installation)
```

**Steps To Reproduce:**
- Install k3s v1.19.5 or below
- run `curl -sfL https://get.k3s.io  | INSTALL_K3S_EXEC="--disable traefik" sh -`

**Expected behavior:**
I'm expecting a few things:
1. The latest version to be installed should match the `latest release` (green label) as shown on the github release page.
2. Only releases present on the github page should be pulled and installed (ie v1.20.2+k3`s1` vs v1.20.0+k3`s2`)
3. (feature request) When upgrading to a new major version v1.19 to v1.20, it would be nice to get a confirmation prompt.
4. (question) How to upgrade while staying on the same major version ?

**Actual behavior:**
Version v1.20.0+k3s2 was being pulled and about to be installed.

**Comment by aureq** [comment]
Note, adding `INSTALL_K3S_CHANNEL=stable` yields the same behavior where version `v1.20.0+k3s2` is being pulled.

**Comment by brandond** [comment]
We have zero control over the 'latest release' label on GitHub. The 'latest' release is whatever tag has the most recent commit timestamp. Since releases are sometimes built in a different order than what semver would consider latest, it should not really be relied on for much of anything. RCs/betas/etc are always left as pre-release. GA releases are left as pre-release until CI completes and all the artifacts are available.

You can find the channel server data at https://github.com/k3s-io/k3s/blob/master/channel.yaml. 'Latest' will give you the most recent GA release according to semver rules. Stable is manually updated, and generally updates to the same as 'latest' after it's been out for a week and doesn't have any identified defects. Versioned channels are available if you want to receive only patches within a specific release train.

This is all described at https://rancher.com/docs/k3s/latest/en/upgrades/basic/

**Comment by scndel** [comment]
I've experienced issue to install latest stable Rancher on latest stable k3s because of this.
I Proposed to align version to match github releases and to ease installation of Rancher (if applicable).
https://github.com/k3s-io/k3s/pull/2824
