### ISSUE TITLE
Integrate S3 Compatible API's for Etcd Snapshot Targets

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#2838]
Thanks for helping us to improve k3s! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A user should be able to store Etcd snapshots to an S3 compatible API.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShylajaDevadiga** [comment]
Validated all verification instructions provided using commit id.
```
k3s version v1.20.5+k3s-a3ec5904
```

**Comment by ShylajaDevadiga** [comment]
Validated using v1.20.5-alpha1+k3s2 on a single node and multi-node setup

- On-demand snapshots stored locally and to s3
- Automated snapshots stored locally as well as to s3
- Restoration from snapshots stored locally and from s3
- Validated quorum loss scenario on a multi-node setup with nodes powered down
- Validated snapshot retention to s3

Related minor issue with snapshot retention https://github.com/k3s-io/k3s/issues/3178
Unrelated to snapshot but impacted due to parsing of '*' in scheduled snapshot creation using install script https://github.com/k3s-io/k3s/issues/3179
Scheduling automated snapshots can be done using config.yaml
