### ISSUE TITLE
Why is K3s still syncing back to a lock file?

### ISSUE THREAD

**Issue by aronchick** [k3s-io/k3s#3087]
I've installed k3s and it works fine ... but when I try to change contexts, I'm getting a weird error:

```
error: open /etc/rancher/k3s/k3s.yaml.lock: permission denied
```

The command I'm using to get this error:
```
KUBECTL_BIN=kubectl; $KUBECTL_BIN config set 'contexts.'`$KUBECTL_BIN config current-context`'.namespace' kubeflow
```

I'm just doing a vanilla install - followed up by a merging of the config file into my core config file.
```
curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
KUBECONFIG=$HOME/.kube/config:/etc/rancher/k3s/k3s.yaml kubectl config view --flatten > $HOME/.kube/config
```

Is there anything I can do to get this to work?

**Comment by Oats87** [comment]
The command you provided looks to be attempting to modify the `/etc/rancher/k3s/k3s.yaml` kubeconfig, which shouldn't really be done. It looks like the user you are calling `kubectl` as may not have permissions to write to that directory, hence the error creating the lock file.

**Comment by aronchick** [comment]
Hmm... does it? I thought the command reads in the /etc/rancher/k3s/k3s.yaml file and then allows you to flatten it into your file (which you have perms for} - or are you talking about the middle command? Wouldn't that just act on my local .kube/config?

**Comment by Oats87** [comment]
> Hmm... does it? I thought the command reads in the /etc/rancher/k3s/k3s.yaml file and then allows you to flatten it into your file (which you have perms for} - or are you talking about the middle command? Wouldn't that just act on my local .kube/config?

The third command snippet you provided will perform a flattening of both `$HOME/.kube/config` and `/etc/rancher/k3s/k3s.yaml` and place them into `$HOME/.kube/config`; however, the second command snippet is what I was referring to in regards to writing to the `/etc/rancher/k3s/k3s.yaml` kubeconfig.

K3s performs some interesting wrapping around `kubectl` -- if you inspect the `kubectl` located in `/usr/local/bin`, it is actually a symlink to `/usr/local/bin/k3s`, which functionally is `kubectl` but has a little bit of logic wrapped into it to default to using `/etc/rancher/k3s/k3s.yaml` (if it exists) as the default kubeconfig if the environment variable `KUBECONFIG` (or flag) isn't set.

This can be traced through:
https://github.com/k3s-io/k3s/blob/master/pkg/cli/kubectl/kubectl.go 
which calls the exported main here: https://github.com/k3s-io/k3s/blob/master/pkg/kubectl/main.go
which calls https://github.com/k3s-io/k3s/blob/master/pkg/server/server.go#L257 which checks for the `GlobalConfig`.

Unfortunately, if you want to modify the kubeconfig and still use the `k3s`-provided `kubectl`, you'll need to explicitly set the `KUBECONFIG` environment variable.

I think there is room for enhancement here though to fix this such that `kubectl` conforms more to expected behavior where it utilizes the `$HOME/.kube/config` if it exists, and otherwise falls back to the `/etc/rancher/k3s/k3s.yaml` (rather than the inverse, which is what it is doing now).

**Comment by aronchick** [comment]
Ahhhhhh I was SO confused why I was getting this message when I already had installed a kubectl. This makes complete sense.

To be clear, I had run the third command already to flatten and change perms, so this was the confusion. Yes, this behavior was unexpected. The flow that I would like:

* Install k3s
* Have an option to write it into my standard .kube/config with my perms and flatten/merge if file already there
* Kubectl has same behavior whether installed with k3s or other service

I've tried messing around with --write-kubeconfig-mode but that didn't seem to help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brandond** [comment]
You can always use your own version of kubectl that doesn't have our special config loading behavior. Just make sure your version is first in the $PATH.

**Comment by aronchick** [comment]
totally understood - it's just super hidden that this is what k3s does (put a custom kubectl in there that is incompatible with standard kubectl behavior)
