### ISSUE TITLE
Add support for --system-default-registry

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3281]
Add support for `--system-default-registry` flag so that K3s core images can be explicitly loaded from a different registry.

This is required to operate K3s in an environment where all images must be pulled from a registry that requires `--image-credential-provider` auth, as the images must be explicitly sourced from the cloud provider's registry instead of transparently pulled from a mirror endpoint by registries.yaml configuration. For example, an EC2-based airgap-like environment where images are required to be hosted on ECR.

**Comment by rancher-max** [comment]
#### Validated system-default-registry flag exists and is working correctly in v1.21.1-rc1+k3s1

- `system-default-registry` exists as a flag for `server` and not `agent`
- Can setup a private registry that uses TLS, trust the certs on the node, and then start k3s using this flag, which will pull its system-level images from the private registry. Validated this on airgapped nodes.
- In order to run other images in the cluster, must also have a registries.yaml configured correctly. This is expected behavior as only the core images will come from the registry in this flag. (The registry in registries.yaml can be the same or different from this one).
