### ISSUE TITLE
install.sh: envvar capture not working as expected for values with spaces or shell-relevant characters

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s#3395]
**Environmental Info:**
K3s Version: 
- 1.19.x
- 1.20.x
- 1.21.x

Node(s) CPU architecture, OS, and Version: 

- k3os (openrc)

Cluster Configuration:

n/a

**Describe the bug:**

Invoking `env K3S_TOKEN="i like pie" install.sh` results in unquoted `K3S_TOKEN=i like pie` in the .env file

**Steps To Reproduce:**
see https://github.com/rancher/k3os/issues/708

**Expected behavior:**

K3S_* envvars with spaces and/or `!` (and other problematic characters) honored

**Actual behavior:**

K3S_* envvars with spaces have their values truncated when read by the openrc service file.

**Additional context / logs:**

- https://github.com/rancher/k3os/issues/708

**Comment by mdrahman-suse** [comment]
**Validated with k3s version: v1.21.5+k3s2 (default version from `install.sh` script**

_Steps and results_
1. Download the `install.sh` script using `wget -O install.sh https://get.k3s.io`
2. Run the install script with `env K3S_TOKEN="i like pie" ./install.sh`
3. Check the env file
```
$ cat /etc/systemd/system/k3s.service.env
K3S_TOKEN='i like pie'
```

**Comment by mdrahman-suse** [comment]
@dweomer While testing this issue, I see a weird behavior and I think its an issue, may be minor
When I perform `env K3S_TOKEN="i like pie !!" ./install.sh` I am seeing in the `env` file that the token is getting saved differently, is that expected? Different as in the token saves the last command I ran instead of `!!`
This is what I see in the `env` file after installation
```
$ cat /etc/systemd/system/k3s.service.env
K3S_TOKEN='i like pie /usr/local/bin/k3s-uninstall.sh'
```
This was the last command that I ran on the session before install `/usr/local/bin/k3s-uninstall.sh`
Please advice

**Comment by brandond** [comment]
You need to put `!!` in single quotes to prevent it from being handled by your shell, otherwise it is expanded out to the last command from your history.

```bash
K3S_TOKEN='i like pie !!' ./install.sh
```

**Comment by dweomer** [comment]
https://tldp.org/LDP/abs/html/histcommands.html

**Comment by mdrahman-suse** [comment]
Sounds good, thanks @brandond @dweomer Closing this
