### ISSUE TITLE
Can /etc/rancher/k3s/config.yaml be used to init k3s-agents?

### ISSUE THREAD

**Issue by hlacik** [k3s-io/k3s#3705]
Hello guys,

So far I am deploying kubernetes master via config.yaml with

```
write-kubeconfig-mode: "0644"
token: xxx

disable:
  - coredns
  - servicelb
  - traefik
  - local-storage
  - metrics-server
```

and executing
standard installer
`curl -sfL https://get.k3s.io | sh -`

I want to be able to init k3s-agent and join server node via config.yaml as well,

however having in config.yaml :
```
write-kubeconfig-mode: "0644"
token: xxx
server: https://172.16.15.8:6443

disable:
  - coredns
  - servicelb
  - traefik
  - local-storage
  - metrics-server

```
and executing
`curl -sfL https://get.k3s.io | sh -` on agent node, is not working. Apparently install script will deploy whole k3s server anyway.

Only solution that works for me is traditionally executing

`curl -sfL https://get.k3s.io | K3S_URL=https://172.16.15.8:6443 K3S_TOKEN=xxx sh -`

and agent gets deployed.

I suppose there is currently no solution using config.yaml to deploy agent and join server?

**Comment by carloscarnero** [comment]
I am deploying the agents with a `config.yaml` file, as per my interpretation of the documentation. Two notes, though:

- The server should be started with `k3s server`, while the agent with `k3s agent`.
- The `disable` array in `config.yaml` should only be defined in the server, AFAICT. Just look at the options for the [server](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#k3s-server-cli-help) and for the [agents](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#k3s-agent-cli-help).

**Comment by hlacik** [comment]
> EDIT: added the `write-kubeconfig-mode` item.

what do you

**Comment by hlacik** [comment]
> * The server should be started with `k3s server`, while the agent with `k3s agent`.

what do you have in config.yaml for agent then?'

**Comment by hlacik** [comment]
> I am deploying the agents with a `config.yaml` file, as per my interpretation of the documentation. Two notes, though:
> 
what do you have in config.yaml for agent, can you share? which alternative to K3S_URL?

> * The server should be started with `k3s server`, while the agent with `k3s agent`.

i do deployment with install script (curl -sfL https://get.k3s.io) , are you suggesting that i should do it manually ?

**Comment by carloscarnero** [comment]
> what do you have in config.yaml for agent, can you share? which alternative to K3S_URL?

This is (almost) all I have in the agents' `config.yaml`:

```yaml
token: 6cd3556deb0da54bca060b4c39479839
server: https://api.example.com:6443
```

And this in the servers':

```yaml
token: 6cd3556deb0da54bca060b4c39479839
server: https://api.example.com:6443

datastore-endpoint: mysql://user:password@tcp(mysql.example.com:3306)/database

write-kubeconfig: /home/administrator/.kube/config
write-kubeconfig-mode: 644

tls-san:
- api.example.com

disable:
- servicelb
- traefik
```

The `token` is a pre-selected random string and is shared among all nodes (servers and agents) and the `server` is just an external Nginx that load balances the API (pointing to the servers, of course.) Note that this is for a cluster that uses an external MySQL database, instead of etcd; and that I removed some non-essential stanzas, like node taints (server) and extra arguments for the kubelets (agents.) 

> i do deployment with install script (curl -sfL https://get.k3s.io) , are you suggesting that i should do it manually ?

That's the point... there are [several ways for deployment](https://rancher.com/docs/k3s/latest/en/installation/install-options/). What I chose, which was mostly dictated by circumstances, was basically:

- Copy the binaries to each node.
- Copy the appropiate `config.yaml` file, as per node role.
- Create a systemd service definition, which have minor differences between servers and agents.
- Enable and start the service.

All of the above, using Ansible. I'm not 100% sure or confident that this is the way to go, but I have been testing this cluster for a couple of weeks, and everything works as expected. Furthermore, I just upgraded from `v1.21.2+k3s1` to `v1.21.3+k3s1` and it worked alright. My main doubt about this deployment scheme is related to cluster initialization. As I understand it, it is only required when using etcd, but... I'm not sure.
