### ISSUE TITLE
Don't start kube-proxy until after all startup hooks are finished; ensure config modified by hooks is sent to clients.

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3725]
In rancher/rke2#1455 it was determined that the intended behavior was not working for multiple reasons:
* kube-proxy is started before the startuphooks are executed
* the configuration struct modified by the RKE2 startuphooks is not reflected in the config sent to the clients

We need to modify K3s to:
* wait for the startup hooks to complete before sending kube-proxy config to the agent
* ensure that any configuration modified by startup hooks is reflected in the data structure sent to clients

**Comment by rancher-max** [comment]
This issue was mostly for a change in k3s that was required to allow a feature in rke2 to work properly. I kept this around pending an rc in order to perform standard sonobuoy and regressions checks, but those will be validated as part of standard patch testing so I will close this issue.

I did confirm using master commit `90960ebf4e7a08df075526f411e3afe06731b01e` that kube-proxy does wait until the server is ready per the new `v1-k3s/readyz` endpoint before attempting to start:
```
Sep 10 18:31:36 ip-172-31-23-183.us-east-2.compute.internal k3s[1839]: time="2021-09-10T18:31:36Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
...
Sep 10 18:31:41 ip-172-31-23-183.us-east-2.compute.internal k3s[1839]: time="2021-09-10T18:31:41Z" level=warning msg="Unable to watch for tunnel endpoints: unknown (get endpoints)"
Sep 10 18:31:41 ip-172-31-23-183.us-east-2.compute.internal k3s[1839]: time="2021-09-10T18:31:41Z" level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --conntrack-max-per-core=0 --conntrack-tcp-timeout-close-wait=0s --conntrack-tcp-timeout-established=0s --healthz-bind-address=127.0.0.1 --hostname-override=ip-172-31-23-183.us-east-2.compute.internal --kubeconfig=/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig --proxy-mode=iptables"
```
