### ISSUE TITLE
Allow setting a custom `node.kubernetes.io/instance-type` node label

### ISSUE THREAD

**Issue by marcbachmann** [k3s-io/k3s#3933]
**Is your feature request related to a problem? Please describe.**
I'd like to set a custom `node.kubernetes.io/instance-type` node label in k3s agents or servers, but it gets overwritten with `k3s`. Is there any technical reason behind it, why that isn't supported? A related issue could be #1916 

```yaml
# /etc/rancher/k3s/config.yaml
...
node-label:
  - "node.kubernetes.io/instance-type=s-8vcpu-16gb"
```

**Describe the solution you'd like**
The `node.kubernetes.io/instance-type=k3s` label should only be used as fallback if no `node.kubernetes.io/instance-type` label is present.

Edit: I just tested setting `beta.kubernetes.io/instance-type=s-8vcpu-16gb`, which properly sets both variables. So the code could just use another condition or getter to not overwrite values passed.

**Comment by brandond** [comment]
K3s has an internal cloud provider that is used to set node external IPs. This is required because nodes are not allowed to set this field for themselves. The code for this is at https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/instances.go#L50, and returns `k3s` as the cloud provider name.

If you want to have nodes show up with the correct metadata and cloud provider ID, you should disable the K3s cloud provider (with --disable-cloud-controller) and deploy the correct out-of-tree cloud provider for wherever you're running K3s.

**Comment by marcbachmann** [comment]
I'll use the cloud provider in my specific case, but there are some customers which can't.
But it's still quite weird that setting `beta.kubernetes.io/instance-type=s-8vcpu-16gb` will configure both labels... Maybe a kubernetes thing.
