### ISSUE TITLE
[release-1.21] etcd member management controller

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#4002]
Backport of: https://github.com/k3s-io/k3s/issues/3973

**Comment by rancher-max** [comment]
#### Validated on release-1.21 branch commit `863512e0555662e4bc72c3722c13c04c62e92386`

- Performed the first 4 steps mentioned in https://github.com/k3s-io/k3s/pull/4001. Note the one difference is the annotation to watch for on the node has a `cattle` in it, so it is: `etcd.k3s.cattle.io/removed-node-name`
- Observed when adding the annotation and it is removed from the etcd cluster, the node goes to a NotReady state and the k3s logs are correctly angry with:
```
Sep 14 23:26:58 ip-172-31-3-152 k3s[1393]: E0914 23:26:58.235065    1393 leaderelection.go:325] error retrieving resource lock kube-system/k3s: etcdserver: server stopped
Sep 14 23:26:58 ip-172-31-3-152 k3s[1393]: E0914 23:26:58.909675    1393 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: server stopped"}: etcdserver: server stopped
Sep 14 23:26:58 ip-172-31-3-152 k3s[1393]: E0914 23:26:58.910196    1393 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: etcdserver: server stopped
```
- Restarting the k3s service on this deleted node adds it back to the etcd cluster as is visible by etcd member list. It does correctly have a different Name there now. Furthermore, the added annotation `etcd.k3s.cattle.io/remove` is set to false, the programmatically added annotation of `etcd.k3s.cattle.io/removed-node-name` is no longer present, and the other related etcd annotation for its name has been properly updated to be the new etcd name value. 
- systemd did not try to restart the service itself, however upon rebooting the node, the service is correctly restarted and rejoins the cluster
- Applying the value as a label instead of an annotation does not have any effect
- Am able to remove the label on a node that has it set to false with no side effects
- Applying the annotation to 2 nodes in a 3 server cluster does NOT cause a quorum loss as both nodes are simply removed from the etcd cluster.
- Am able to apply the label, restart the service, apply the label again, and delete the node after it is removed from etcd.
- Am able to apply the label and see proper handling after an upgrade, but opened #4023 for potentially related issue due to node deletion after an upgrade.
