### ISSUE TITLE
Installation not working on Raspberry Pi Buster OS

### ISSUE THREAD

**Issue by hitenlulla** [k3s-io/k3s#4461]
The installation script given on the website : 'curl -sfL https://get.k3s.io | sh -' is not working, the raspberry pi installation stops at the point of dowloading. 

root@raspberrypi:~# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.21.5+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/k3s-arm64

Note the internet is working properly yet it is stuck at downloading.

**Comment by brandond** [comment]
What do you get from running
`curl -vsOL https://github.com/k3s-io/k3s/releases/download/v1.21.5+k3s2/k3s-arm64`

**Comment by hitenlulla** [comment]
Done sir, It took quite a long time to downlod the file. Also I need one more help, can you tell me how can I install NodeRed on k3s. I'm not able to find any YAML script on the internet.

**Comment by brandond** [comment]
> It took quite a long time to download the file.

I suspect that the download was timing out or otherwise failing when you're running the install script. The file is not very large, only ~50mb. If your internet connection is slow or unreliable, you might consider manually downloading the binary and running the install script with INSTALL_K3S_SKIP_DOWNLOAD.
