### ISSUE TITLE
Need to enable Ping so Rancher HA healthcheck passes

### ISSUE THREAD

**Issue by tfiduccia** [k3s-io/k3s#458]
**Describe the bug**
Tried to create Rancher HA machine using k3s and it won't pass healthcheck

**To Reproduce**
1.  Create 3 ubuntu machines on AWS
2.  Setup Amazon load balancer for those machine
3.  Ssh  on first machine and install k3s & start server
4.  Add other two machine as k3s agents
5.  Add Helm
6.  Install Tiller
7.  Install Ingress & Cert
8.  Install Rancher using ha/Helm-rancher directions

**Expected behavior**
Rancher HA running on k3s machine.

**Additional context**
Need to enable Ping for k3s
![image](https://user-images.githubusercontent.com/11514927/57404570-1c452180-7191-11e9-9ae4-d00942259f65.png)

**Comment by erikwilson** [comment]
Since the default ping setup for AWS ELBs is http://instance:80/index.html it seems like it might be a port configuration issue with the Rancher install. Are you able to verify that Rancher is accessible from port 80 on the instances? If it is redirecting to 443 that may be causing issues with ping also.

I have a feeling this is not something we should change in k3s (creating a built-in web server running on port 80 is likely to be problematic since traefik install by default creates a loadbalancer for that port). I think it may be better to select another ping method (https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html), or ensure there is a working service on port 80 running in k3s.

**Comment by deniseschannon** [comment]
I think we need to address this docs issue as well: https://github.com/rancher/docs/issues/1241

**Comment by caroline-suse-rancher** [comment]
Closing due to age
