### ISSUE TITLE
How to reset /etc/rancher/k3s/k3s.yaml

### ISSUE THREAD

**Issue by turowicz** [k3s-io/k3s#4582]
I would like to regenerate `/etc/rancher/k3s/k3s.yaml` file as we are migrating to user-specific accounts and I want everyone to lose the admin access.

**Comment by turowicz** [comment]
cc @brandond

**Comment by ChristianCiach** [comment]
Take this with a grain of salt, because I've only checked the code on my phone and I am not too familiar with the code base anyway, but...

According to the code in https://github.com/k3s-io/k3s/blob/master/pkg/daemons/control/deps/deps.go you should be able to just delete the files `client-admin.crt` and `client-admin.key` found at `/var/lib/rancher/k3s/tls/` and then restart the k3s server. If I understand the code correctly, k3s should treat the absence of the file the same as an (almost) expired certificate, so it should be recreated.

**Comment by ChristianCiach** [comment]
I've given this a bit more thought: Recreating the client certificate may not invalidate the old certificate. You may need to also delete the files `client-ca.(crt|key)`. Please try this on a throwaway-cluster before attempting this in production..

**Comment by brandond** [comment]
I'm not sure what you mean by "resetting" it. The admin certificate is signed by the cluster CA; if you've given copies of this file to other users in your organization, there is no way to invalidate the admin client certificate embedded in the kubeconfig short of rebuilding the cluster.

**Comment by turowicz** [comment]
OK I see it was a really bad idea.

I have now revoked the certificate from users by force and terror.
