### ISSUE TITLE
Worker unable to communicate with master as soon as a service of type LoadBalancer is created

### ISSUE THREAD

**Issue by CiraciNicolo** [k3s-io/k3s#5000]
**Environmental Info:**
K3s Version: 

k3s version v1.22.5+k3s1 (405bf79d)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Linux redacted 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server, 1 agent

**Describe the bug:**

The worker is unable to communicate with the server as soon as a service of type LoadBalancer is created. On the worker, the kube-ipvs0 interface is assigned to the master ip address and therefore every connection is passed trough this interface that cannot talk to the master.

**Steps To Reproduce:**
- Installed K3s Server with this conf:
```/usr/local/bin/k3s \
    server \
        '--disable=traefik' \
        '--disable=coredns' \
        '--cluster-cidr=10.69.0.0/16' \
        '--service-cidr=10.70.0.0/16' \
        '--service-node-port-range=1-65535' \
        '--cluster-dns=10.0.70.10' \
        '--flannel-backend=ipsec' \
        '--kube-proxy-arg=proxy-mode=ipvs'
```
- Installed K3s worker with this conf: 
```/usr/local/bin/k3s \
    agent \
        '--node-external-ip=100.64.0.2' \
        '--kube-proxy-arg=proxy-mode=ipvs'
```
- Install haproxy-ingress controller in DaemonSet configuration, that create multiple service of type LoadBalancer, with this configuration:
```controller:
  hostNetwork: true
  kind: Daemonset
  daemonset:
    useHostPort: true
  stats:
    enabled: true
```

**Expected behavior:**

Master node should be reachable after worker joined cluster.

**Actual behavior:**
Master node's IP address was token over by worker unless haproxy-ingress is removed

**Additional context / logs:**
Already followed "suggested" resolution on https://github.com/k3s-io/k3s/issues/2804, but with no luck. I don't think the issue is linked to haproxy-ingress, but a more general problem with klipper. The two instances are on the same network (/24). 

In the screenshot below you can see the issue: the master ip is assigned to kube-ipvs0 and k3s-agent cannot comunicate with the worker.

![Screenshot 2022-01-20 at 14 20 35](https://user-images.githubusercontent.com/910971/150346922-ce9b1464-7712-4bbe-84bc-130f5053e089.png)

**Comment by manuelbuil** [comment]
Yes, this problem is well explained here: https://comphilip.wordpress.com/2021/05/30/k3s-thing-better-ipvs-solution/

When a service of `type: LoadBalancer` gets created, the k3s servicelb controller will set the node's external ip as the external ip for the service. However, if there is no external ip defined, then it takes the node ip. This happens for all nodes in the cluster. In your case, you defined an external ip for the agent but not for the server, so your `type: LoadBalancer` service gets two external ips: the external-ip of the node and the ip of the server. As a result, you get the problem you saw.

Can you try defining an external-ip for the server too?

**Comment by CiraciNicolo** [comment]
An external ip in the same "fake" subnet? By the way, using iptables as proxy-mode seems to be a valid alternative.

![Screenshot 2022-01-20 at 15 00 01](https://user-images.githubusercontent.com/910971/150352882-766e630c-a096-4126-8899-e486f25e6d6b.png)

**Comment by manuelbuil** [comment]
> An external ip in the same "fake" subnet? By the way, using iptables as proxy-mode seems to be a valid alternative.
> 
> ![Screenshot 2022-01-20 at 15 00 01](https://user-images.githubusercontent.com/910971/150352882-766e630c-a096-4126-8899-e486f25e6d6b.png)

If the kube-proxy is in iptables mode you will not have this issue because no interface in your node will get the $master_node_ip. When you set kube-proxy in ipvs mode, a new interface kube-ipvs0 gets created in your node. That interface will get the external-ips of your services, i.e. it will get $master_node_ip if you don't define an external ip. Therefore, when the agent wants to reach kube-api, instead of sending packets to the server node, the packets will be sent to your local kube-ipvs0 interface

**Comment by CiraciNicolo** [comment]
And setting a fake external ip for both the server and the agent should fix the issue? Using ipvs as proxy-mode.

**Comment by manuelbuil** [comment]
Yes but if you want to access the service from outside the cluster, that "fake" external ip needs to be routable. In other words, a host not part of the cluster that wants to access the service needs to have a route to reach that external ip

**Comment by CiraciNicolo** [comment]
Ok, thanks for the clarification. For this use case iptables is the best :)
