### ISSUE TITLE
Install only agent with config file;  need more exemple / clear documentation ...

### ISSUE THREAD

**Issue by andrelec1** [k3s-io/k3s#5104]
So ... installing K3S is : `curl -sfL https://get.k3s.io | sh -`
Installing K3S agent is more like : `curl -sfL https://get.k3s.io | env K3S_SERVER=... K3S_TOKEN=... sh -`

But i already have my /etc/rancher/k3s/config.yaml file created ( and populed ) ...

So how to install only the agent without re-specified all value in the commande ? 

after reading the unclear documentation seem to be `curl -sfL https://get.k3s.io | env INSTALL_K3S_EXEC=agent sh -`
but that remove the k3s folder with my config.yaml  !

**Comment by brandond** [comment]
K3s does not ever write a config.yaml file. You may use a config file in place of any environment variable or CLI flag, with the caveat that installer variables that determine whether to install an agent or server will not be read from the config file, so you must specifically tell the installer to create an agent. The yaml keys are the same as CLI flag names.

Instead of doing
```bash
curl -sfL https://get.k3s.io | env K3S_SERVER=... K3S_TOKEN=... sh -` 
```

You could instead do:
```bash
mkdir -p /etc/rancher/k3s
cat <<EOF >/etc/rancher/k3s/config.yaml
server: https://server:6443
token: my-token
EOF
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=agent sh -
``

**Comment by andrelec1** [comment]
> The uninstaller will remove /etc/rancher/k3s; is that perhaps what you're seeing?
Ho i run the uninstaller when i see the curl command didn't install the agent on my first try, so you right ! 

i already have a little scrip that generate the config.yam with good interface ip and good name for my nodes 
also download a registries.yaml ^^

I think just adding `curl -sfL https://get.k3s.io | env INSTALL_K3S_EXEC=agent sh -` as another option to install only agents in the qwick-start guide is a good things ...

**Comment by caroline-suse-rancher** [comment]
Closing as this isn't in our current plans
