### ISSUE TITLE
Not able to authenticate Service account token

### ISSUE THREAD

**Issue by parekhha** [k3s-io/k3s#5250]
**Environmental Info:**
K3s Version: v1.21.5+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux  5.3.18-22-default #1 SMP (720aeba) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 master

**Describe the bug:**
Created service account token and tried to authenticate with k3s api using that token but getting unauthorized error

**Steps To Reproduce:**
1) Create Ca cert and  keep that under /var/lib/rancher/k3s/server/tls
       client-ca.key
       client-ca.crt
        server-ca.key
        server-ca.crt
        request-header-ca.crt
        request-header-ca.key

2) Install k3s cluster with external datastore

**Expected behavior:**
Should be able to successfully authenticate using service account token.

**Actual behavior:**
Not able to autheticate using service account token

**Additional context / logs:**
Getting below error in k3s logs
3942 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"

**Comment by brandond** [comment]
Did you create the certificates yourself, or are you using the ones created by K3s? What steps did you follow to create the service account token?

**Comment by parekhha** [comment]
I have created certificate by my self.
To create service account, I have used following command,
kubectl create serviceaccount --namespace xxxx user1 --dry-run=client -o yaml | kubectl apply -f -

Created appropriate cluster roles and cluster rolebindings
Then I got token from secret. Used that token for authentication.

**Comment by brandond** [comment]
Are you sure you created the CAs correctly? Are you using a fresh SQL database for the datastore, or was it previously used for a different cluster and/or with different certificates?

**Comment by parekhha** [comment]
Yes these same certificate and approach was working for k3s 1.17.3 We are using etcd as external datastore.

**Comment by brandond** [comment]
Recent releases of K3s now reconcile the certificates in the datastore against those on disk. If you want to use custom certificates, they must be on disk on the first node before it is started for the first time so that they can be written into the datastore for use by other nodes when bootstrapping. If you try to change the certificates after the fact, they will be overwritten with the ones in the datastore. Can you confirm that your custom certs were in place before the datastore was used for the first time?

**Comment by parekhha** [comment]
Yes it was present before running k3s. and all three k3s node is up and ready.

**Comment by brandond** [comment]
The error you're getting suggests it was signed by the wrong certificate. Can you post the token itself?

**Comment by parekhha** [comment]
Which certificate and key will be used to signed this token ?

**Comment by pradeep-av** [comment]
@brandond here's the token
`
eyJhbGciOiJSUzI1NiIsImtpZCI6Im9PNUpwMG5jc0VvNjZlT01ZRllJeUYyZW01V0RMdnd4RjVpUUN3ZUNsc1EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi02dzlwdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjFiNzU5ZDQyLWRlY2UtNGYxOC1hZWI0LTVkZDE1MGNlYzBlNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.pHEWyF_P_uLZ4bTIPW0qAmvIQ8Ox5EbK6TeT4usMERULlVWyC0qlyZLTBJ8_RuYdhSQ6klqiZrXzdoIRHHFEuZzndCODqebciM1d1i2MveVUfUrSgqc42R_DUC5rG0Ae0LuWsev_RbuURe68kC3KhSFKniv8lFyjmwkh7y8SsUiojnziSP582TEmQsyB1S9Yky6wqze5WrvC2oxt6lF5r8yzSjBolUcrWhFI4VDR5dlDrsqxkw7rHTsxNWZ8fVfnBEGe8rRrdUNTMpjWViorudL5qXoJUiV4e__sSp-f484M3LNDXavLli-HhcL5LT7t-cfsVszBNgo3VFwk2zoRig
`

**Comment by pradeep-av** [comment]
@brandond The history of this issue is that we tried to bring up a HA k3s cluster with external etcd datastore. We use the same set of steps that we followed for 1.17.x version. On fresh install we hit an issue similar to - https://githubhot.com/repo/k3s-io/k3s/issues/3888 and hence we recreated the setup with the --token <some-random-string> option. After that the cluster came up but we hit this issue of service account token validation error. While debugging, we removed --token from the systemd definition of k3s and restarted the service and the token validation works like a charm.

So without --token option we hit the clustering problem, with it we hit the service account token issue. So not sure how to proceed here

**Comment by brandond** [comment]
> we tried to bring up a HA k3s cluster with external etcd datastore
> we recreated the setup with the --token option. After that the cluster came up but we hit this issue of service account token validation error. While debugging, we removed --token from the systemd definition of k3s and restarted the service and the token validation works like a charm.

Did you completely wipe the datastore on the external etcd server and terminate all running pods between these steps? Changing the token on an existing cluster is not supported. If you reuse the same datastore, it is considered the same cluster because the data from the old cluster still exists. Trying to change the token or replace the cluster CA certificates will cause all kinds of weird issues, including invalidating tokens signed by the old cluster CA.
