### ISSUE TITLE
k3s-apiserver-lb-controller watches endpoints for etcd-only nodes even when etcd is not enabled

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5389]
Seeing this when updating Kubernetes to 1.24.0-beta.0. Not sure why it's not showing up on master builds with 1.23; perhaps the current grpc version is swallowing the error.

```
{"level":"warn","ts":"2022-04-05T22:56:04.629Z","logger":"etcd-client","caller":"v3@v3.5.1-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc002337340/kine.sock","attempt":0,"error":"rpc error: code = Unknown desc = put is not supported"}
ERRO[0076] error syncing 'default/kubernetes': handler k3s-apiserver-lb-controller: rpc error: code = Unknown desc = put is not supported, requeuing
```

The error somewhat expected since Kine doesn't support the Put operation. On the other hand, this controller shouldn't be running at all when not using embedded etcd, as there are no etcd-only nodes without etcd.

**Comment by rancher-max** [comment]
I don't see "managed etcd" in the logs even on v1.23.5+k3s1. I'm validating with the following steps:
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.6-rc1+k3s1  INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644" sh -
...
$ journalctl -eu k3s | grep -i "managed etcd"
```
Note that when using managed etcd (via adding in the `--cluster-init` flag in the install exec args) this returns something.

I did confirm that this still does not show anything on v1.23.6-rc1+k3s1, but I think I'm doing something wrong in my validation since it is the same behavior for me as in v1.23.5. @brandond If that looks fine to you we can close this, otherwise I need input on how to proceed here.
