### ISSUE TITLE
Validate Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#5443]
https://ubuntu.com/about/release-cycle -- We should validate this in k3s when this is available.

**Comment by mankuen** [comment]
Ubuntu 22.04 / 21.10 on Raspberry Pi needs to install extra kernel modules with `sudo apt install linux-modules-extra-raspi` before starting k3s, otherwise k3s will keep restarting.
I think this might be a key piece of information for Raspberry Pi users, perhaps a necessary remarks in the documentation or verification in the installation script.

**Comment by prisben** [comment]
> Ubuntu 22.04 / 21.10 on Raspberry Pi needs to install extra kernel modules with `sudo apt install linux-modules-extra-raspi` before starting k3s, otherwise k3s will keep restarting. I think this might be a key piece of information for Raspberry Pi users, perhaps a necessary remarks in the documentation or verification in the installation script.

Lifesaver! This should be definitely put in the documentation

**Comment by bguzman-3pillar** [comment]
Validated using these versions:
`v1.21.12+k3s1, v1.22.9+k3s1, v1.23.6+k3s1`
AMI used `ami-03fbae4d2f599cc12 `

Test validated:
- Fresh Installation and sonobuoy execution
- Run functional test on imported k3s cluster on Rancher
- Validate installation with docker CRI 
- Upgrade SUC k3s native with workloads
- Install k3s as local management cluster for Rancher

**Comment by dcdennis** [comment]
Need a reboot after installing extra modules for ubuntu on Pi.
```
sudo apt install linux-modules-extra-raspi && reboot
```
