### ISSUE TITLE
[Question] Any plan to contribute this back to Kubernetes

### ISSUE THREAD

**Issue by gyliu513** [k3s-io/k3s#548]
I found that this repo actually have two code base, one is pruned kubernetes and another is k3s, two questions here:

1) Why host the pruned k8s and k3s code in same repo?
2) Any plan to contribute the pruned k8s to k8s community?

**Comment by ibuildthecloud** [comment]
1. Most legacy.  k3s used to be all one code base.  It was the k8s source plus a bunch of new code.  Then we separated out to two separate packages.  Now that it's here it's hard to ever move and not break old builds.
2. Yes.  We are continuing to refine the set the patches on k8s so that they can be upstreaming.  The first area of focus is developing an approach to the sqlite that can be done without modifying upstream.  Most info to come there...

**Comment by gyliu513** [comment]
> Yes. We are continuing to refine the set the patches on k8s so that they can be upstreaming. The first area of focus is developing an approach to the sqlite that can be done without modifying upstream. Most info to come there...

Thanks @ibuildthecloud , this is really helpful! Do you have a timeline when this can be upstreamed? ;-)

**Comment by brandond** [comment]
Closing due to age. K3s is moving to CNCF and we have another issue for getting rid of carried patches.
