### ISSUE TITLE
[release-1.23] Backport fixes/enhancements from master

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5595]
Backport bugfixes and enhancements from master to release-1.23
* https://github.com/k3s-io/k3s/pull/5560
* https://github.com/k3s-io/k3s/pull/5554

**Comment by rancher-max** [comment]
### Validated using release-1.23 branch commit `f7dc7b95566a2a36ded376d52ca2734c44ca4824`
---
#### [Remove objects when removed from manifests](https://github.com/k3s-io/k3s/pull/5560)
- This is a **very** specific use case as it is functional only when clearing the contents of the file from the specific node.
- Confirmed that deleting the manifest file does _not_ remove the k8s objects. 
- Put the same file contents on a different node in the cluster under a different file name. Saw errors when trying to apply:
```
May 23 20:47:16 ip-172-31-26-32 k3s[1614]: time="2022-05-23T20:47:16Z" level=info msg="Event(v1.ObjectReference{Kind:\"Addon\", Namespace:\"kube-system\", Name:\"thisnode\", UID:\"bb6104bc-0ce6-47cc-a73a-a98c60da9b04\", APIVersion:\"k3s.cattle.io/v1\", ResourceVersion:\"10466\", FieldPath:\"\"}): type: 'Warning' reason: 'ApplyManifestFailed' Applying manifest at \"/var/lib/rancher/k3s/server/manifests/thisnode.yaml\" failed: failed to create default/nginx-nodeport-svc /v1, Kind=Service for  kube-system/thisnode: Service \"nginx-nodeport-svc\" is invalid: spec.ports[0].nodePort: Invalid value: 30096: provided port is already allocated"
May 23 20:47:31 ip-172-31-26-32 k3s[1614]: time="2022-05-23T20:47:31Z" level=info msg="Event(v1.ObjectReference{Kind:\"Addon\", Namespace:\"kube-system\", Name:\"thisnode\", UID:\"bb6104bc-0ce6-47cc-a73a-a98c60da9b04\", APIVersion:\"k3s.cattle.io/v1\", ResourceVersion:\"10466\", FieldPath:\"\"}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at \"/var/lib/rancher/k3s/server/manifests/thisnode.yaml\""
```
- Put the same file contents on a different node in the cluster under the same file name. Did not see errors or any apply of the manifest happen. This is good. I then deleted the contents of that file from that node. Still nothing happened. This is unexpected to me.
- Instead of directly clearing file contents, it is also possible to just delete the file from the node, then touch the file back. 
- It seems to be best practice to do the same actions on all nodes (same file names, same contents) in case of rotating nodes in and out and wanting to use this feature.

#### [Bump dynamiclistener to v0.3.3](https://github.com/k3s-io/k3s/pull/5554)
- Installs and upgrades are successful
- General k8s functionality appears to be working
