### ISSUE TITLE
[release-1.23] Observed a panic: "invalid memory address or nil pointer dereference" repeated in syslog

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5800]
Backport to branch `release-1.23`:
* #5762

**Comment by mdrahman-suse** [comment]
### Validated on v1.23.8-rc1+k3s2
 
## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Linux 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
 
*Cluster Configuration:*

```
Single node
```
 
*Config.yaml:*

```
N/A
```
 
*Additional files*

- test.yaml (with unset service IPFamilyPolicy)
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: ExternalName
  externalName: test.example.com
```
 
## Testing Steps

### Fresh install
1. Install k3s with v1.23.8+k3s1 `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.8+k3s1 sh -s - server --write-kubeconfig-mode 644`
2. Ensure the cluster is up `kubectl get nodes,pods -A- o wide`
3. Deploy test.yaml `kubectl apply -f test.yaml`
4. Ensure service is deployed `kubectl get svc`

### Upgrade
1. Install k3s with v1.23.7+k3s1 `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.7+k3s1 sh -s - server --write-kubeconfig-mode 644`
2. Ensure the cluster is up `kubectl get nodes,pods -A- o wide`
3. Upgrade to v1.23.8+k3s1 `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.8+k3s1 sh -s - server --write-kubeconfig-mode 644`
4. Deploy test.yaml `kubectl apply -f test.yaml`
5. Ensure service is deployed `kubectl get svc`
 
**Replication Results:**
- k3s version used for replication:

- Search for `panic` in the logs
- Observe the error
```
$ journalctl -eu k3s | grep -i panic
Jul 05 22:04:31 ip-172-31-9-214 k3s[25439]: E0705 22:04:31.197852   25439 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 05 22:04:31 ip-172-31-9-214 k3s[25439]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x41edd60, 0x7b59c60})
Jul 05 22:04:31 ip-172-31-9-214 k3s[25439]: panic({0x41edd60, 0x7b59c60})
Jul 05 22:04:31 ip-172-31-9-214 k3s[25439]:         /usr/local/go/src/runtime/panic.go:1038 +0x215
```

**Validation Results:**
- k3s version used for validation:

```
k3s version v1.23.8-rc1+k3s2 (fe3cecc2)
go version go1.17.5
```
- Perform same steps as above, instead of 1.23.8+k3s1 use v1.23.8-rc1+k3s2
 

- No panic was observed upon service deployment
