### ISSUE TITLE
[Epic] Validate newer external database versions

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#5859]
**Is your feature request related to a problem? Please describe.**
Our current list of databases that we validate against are becoming stale:
https://rancher.com/docs/k3s/latest/en/installation/datastore/
-  PostgreSQL (certified against versions 10.7 and 11.5)
-  MySQL (certified against version 5.7)
-  MariaDB (certified against version 10.3.20)
-  etcd (certified against version 3.3.15)
Most of these versions are quite old, and most are set for EOL in 2023. 

**Describe the solution you'd like**
We need to validate K3s against newer versions of these databases:
- MySQL 8.0
- MariaDB 10.6 
- PostgreSQL 14.4 
- etcd 3.5 

Theses newer DBs all EOL in 2026, which expands coverage for a few more years.

**Comment by rancher-max** [comment]
I have currently validated the following versions using RDS instances:
- MySQL 8.0.28 (used `v1.23.9+k3s1`)
- PostgreSQL 14.2-R1 (used `v1.24.3+k3s1`)
- MariaDB 10.6.8 (used `v1.22.12+k3s1`)

**Comment by rancher-max** [comment]
Validated external etcd using v3.5.4. As all four DBs from this issue have now been validated, the only remaining step here is to update the doc and then we can close this out. @dereknola since you're working on the new doc migration, do you want to do that as part of your work, or want me to take that up when it's finished?

**Comment by dereknola** [comment]
I can do it

**Comment by dereknola** [comment]
Closed as complete! Documentation update is live.
