### ISSUE TITLE
Splitting internal and external traffic

### ISSUE THREAD

**Issue by starkers** [k3s-io/k3s#594]
Just a question.. I've been trying to build a cluster on some 'cloud' VMs.. (I've meshed them all with a `wg0` each).. My intentions are to encapsulate all inter-nodal traffic over their secondary (wireguard) NICs but to allow traffic in on their public `eth0`'s..

There are some challenges here because the wireguard interface probably doesn't play nicely with stuff like ARP... anyway.. Even if I set `--node-ip` to the internal IP, I'm still seeing the vxlan port traffic across their `eth0` devices.. I would like to know if I'm simply missing something simple here or am I in uncharted waters here?  

Maybe it's a flag I didn't notice or maybe I just need to find a setting for flannel or try a different CNI SDN?

**Comment by erikwilson** [comment]
I am curious if the --flannel-iface flag might be helpful, where it may need to be set to wg0.

**Comment by jbhannah** [comment]
I've been tinkering with a [similar setup](https://jbhannah.net/articles/k3s-over-watchguard-with-kilo) on a VPS host that doesn't provide internal IPs, and @erikwilson, yes — `--flannel-iface=wg0` is how I've gotten intra-cluster traffic to go over the encrypted interface. I had been wrestling with getting the public and Wireguard IPs to reflect correctly as each node's external and internal IP addresses when I switched to Kilo (and am now trying out `--flannel-backend=wireguard` because Kilo is looking for a `/var/lib/rancher/k3s/agent/kubeconfig.yaml` file that doesn't appear to exist anymore?), but I think there was a command line flag added since then that seems like it would accomplish that.

**Comment by brandond** [comment]
Closing due to age. The flannel wireguard backend works fine at the moment as far as I know.
