### ISSUE TITLE
[Release 1.22] NodeIP autodetection in case of dualstack node

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#5958]
Backport for #5918 and #5491

**Comment by est-suse** [comment]
Hi @rbrtbnfgl, 

When I trying to replicate this issue on 1.22, is not happening, please refer to image attached:
![image](https://user-images.githubusercontent.com/106194120/183979173-60dfdd41-8660-47b8-ac05-8199d263d578.png)

Using the Commit 2b13d70afd6f324604c2e9e7d48ad9398aeaf437

This issue is happening:

![image](https://user-images.githubusercontent.com/106194120/183979983-3d6136b9-c42a-4986-99dd-c91688b2e919.png)


Could you please take a look and let me know.

Thanks

**Comment by rbrtbnfgl** [comment]
The check for the mismatch between NodeIP and ClusterCIDR was implemented from 1.23 and not backported on 1.22 (I backported it on this PR), so the error that doesn't occur is expected.
The PR fixes the missing IPv6 autodetection also for 1.22: in case of a dualstack node when the nodeIP is not specified if you check the internalIP of the node only the IPv4 is configured, with this PR it configures both IPv4 and IPv6.

**Comment by est-suse** [comment]
hi @rbrtbnfgl, The VM was created and configure for Both IPV4 and IPV6
![image](https://user-images.githubusercontent.com/106194120/184146031-fe97b63a-080f-489a-9346-2d9dd3c0cd3f.png)

This is the Config.yaml:

write-kubeconfig-mode: 644
token: summer
cluster-cidr: 10.42.0.0/16,2001:cafe:43:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:44:1::/112
flannel-iface: "ens5"
disable-network-policy: true
flannel-ipv6-masq: true
cluster-init: true

**Comment by rbrtbnfgl** [comment]
When you run
```
kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.addresses[?(@.type == "InternalIP")].address}{"\n"}{end}'
```
Before the PR you should get
```
Node-name IPv4Addr
```
After the merge you should get
```
Node-name IPv4Addr IPv6Addr
```

**Comment by est-suse** [comment]
Validated on 1.22 branch with commit https://github.com/k3s-io/k3s/commit/2b13d70afd6f324604c2e9e7d48ad9398aeaf437
Environment Details
Infrastructure

 Cloud
 Hosted
Node(s) CPU architecture, OS, and Version:

   Static hostname: ip-192-168-23-0
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec2b159251fd2faee9b6b668fae4d9b9
           Boot ID: 6f780fd9979c470f887974b17f1f1096
    Virtualization: kvm
  Operating System: Ubuntu 20.04.4 LTS
            Kernel: Linux 5.13.0-1029-aws
      Architecture: x86-64

Single node
Config.yaml:

write-kubeconfig-mode: 644
token: summer
cluster-cidr: 10.42.0.0/16,2001:cafe:43:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:44:1::/112
flannel-iface: "ens5"
disable-network-policy: true
flannel-ipv6-masq: true
cluster-init: true
Testing Steps
Copy config.yaml
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
Install k3s
For replication: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.23.9+k3s1 sh -
For validation: curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=d04af60aad053ec94e60c986bf4c70cdbfc9e11c sh -
Ensure k3s cluster is up
Replication Results:

k3s version used for replication:
This issue was not back-ported to 1.22 based on Roberto B comments.
Validation Results:

k3s version used for validation:
k3s version v1.22.12+k3s-2b13d70a
go version go1.17.5

The cluster comes up successfully and no error is observed
$ journalctl -xeu k3s.service | grep 'cluster-cidr:'

$ kubectl get nodes,pods -A -o wide

NAME                   STATUS   ROLES                       AGE   VERSION                 INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
node/ip-192-168-23-0   Ready    control-plane,etcd,master   36m   v1.22.12+k3s-2b13d70a   192.168.23.0   <none>        Ubuntu 20.04.4 LTS   5.13.0-1029-aws   containerd://1.5.13-k3s1

NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE   IP          NODE              NOMINATED NODE   READINESS GATES
kube-system   pod/coredns-7796b77cd4-847qb                  1/1     Running     0          35m   10.42.0.3   ip-192-168-23-0   <none>           <none>
kube-system   pod/helm-install-traefik-crd-p6plb            0/1     Completed   0          35m   10.42.0.2   ip-192-168-23-0   <none>           <none>
kube-system   pod/helm-install-traefik-z9nwf                0/1     Completed   2          35m   10.42.0.6   ip-192-168-23-0   <none>           <none>
kube-system   pod/local-path-provisioner-84bb864455-ptgs4   1/1     Running     0          35m   10.42.0.4   ip-192-168-23-0   <none>           <none>
kube-system   pod/metrics-server-ff9dbcb6c-kgkw9            1/1     Running     0          35m   10.42.0.5   ip-192-168-23-0   <none>           <none>
kube-system   pod/svclb-traefik-nnr5t                       2/2     Running     0          35m   10.42.0.7   ip-192-168-23-0   <none>           <none>
kube-system   pod/traefik-d497b4cb6-7dkwd                   1/1     Running     0          35m   10.42.0.8   ip-192-168-23-0   <none>           <none>


Additional context / logs:

results of the command kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.addresses[?(@.type == "InternalIP")].address}{"\n"}{end}'
ip-192-168-23-0 192.168.23.0 2600:1f1c:ab4:ee48:4243:210f:54e7:e368


Validated with ingress, hostport, nodeport and ran though dual-stack testing
