### ISSUE TITLE
Node status with NotReady after import image!

### ISSUE THREAD

**Issue by PuppetA17** [k3s-io/k3s#5990]
**Environmental Info:**
K3s Version: 
k3s version v1.19.16+k3s- ()

Node(s) CPU architecture, OS, and Version: 
Linux iZ2ze57vwreom23zkxvl6qZ 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3servers

**Describe the bug:**
I have an image with a size of about 3 GB. After uploading this image to a certain master node, and then using K3s ctr i import image, the node status changes to NotReady. It is suspected that the import image is full of disk IO,k3s master node strongly dependent on disk performance. But I need to upload the image to the master node, how to solve this problem?

**Steps To Reproduce:**
- Installed K3s
- Deploy a 3master cluster
- Upload a very large image to the master node
- Import images using K3s ctr i import
- Observe the status of the node. If you don't repeat, you can run some high-load applications on the primary node, and then try to import. The node state will be changed to NotReady

**Expected behavior:**
The mirror is imported normally, and the node status is Ready.

**Actual behavior:**
There is a probability that the import of the image failed, and the node status is NotReady

**Comment by brandond** [comment]
> I have an image with a size of about 3 GB. After uploading this image to a certain master node, and then using K3s ctr i import image, the node status changes to NotReady. It is suspected that the import image is full of disk IO,k3s master node strongly dependent on disk performance. But I need to upload the image to the master node, how to solve this problem?

If the basic act of importing an image is sufficient to cause IO latency to spike unacceptably, then your disk is too slow. You options would be:
* Use faster disk (when using etcd, SSD is basically a requirement)
* Put etcd and the containerd image store on independent disks
* Import the image to a private registry, instead of importing it directly into the local image store. Note that this may not solve the issue, as the image will still be pulled down at some point.
