### ISSUE TITLE
Why doesn't k3s set the default certificate validity period to 10 years?

### ISSUE THREAD

**Issue by MagicStarTrace** [k3s-io/k3s#6101]
![image](https://user-images.githubusercontent.com/15685376/188543487-f819752e-e316-4baf-b6c8-b421bad22bbe.png)
![image](https://user-images.githubusercontent.com/15685376/188543831-c583f0b0-d103-442f-ac0e-e334b621c8e8.png)

The certificate seems to have expired, what should I do now?

**Comment by brandond** [comment]
That's not why it's exiting, according to the logs it's exiting because you passed an unknown CLI flag.

Best practice is not to issue leaf certificates for more than several months to a year. The K3s CA certificates are valid for 10 years, but the server and client certs are only valid for 1 year, and are automatically renewed when the service is starting if they are within 90 days of expiration.

**Comment by MagicStarTrace** [comment]
I see a configuration for etcd-arg in /etc/rancher/k3s/config.yaml. ["experimental-initial-corrupt-check=true"] Removing it and restarting seems to restore

**Comment by dereknola** [comment]
Closing this issue as resolved. Feel free to reopen if the issue persists.
