### ISSUE TITLE
Missing housekeeping options in hyperkube for kubelet

### ISSUE THREAD

**Issue by nmiculinic** [k3s-io/k3s#63]
```
--global-housekeeping-interval duration
--housekeeping-interval duration
```

options are missing in the hyperkube kubelet edition. Setting this to higher value improved kubelet perfomance footprint.

**Comment by ibuildthecloud** [comment]
That's a good point.  I believe those are cadvisor arguments.  Right now we totally messed up cadvisor.  We tried to strip out some of the cruft because it supports things like mesos and rkt which had big dependencies, but we didn't do a good job.  We need to address this.  Kubelet metrics in general I believe are not functioning properly.

**Comment by nmiculinic** [comment]
In my experience, by that I mean pprofing the kubelet on ARM IoT deployment, most of CPU usage goes to housekeeping, go runtime, system calls, and cadvisor stuff. 

So yeah, I'd love to stip as much out as possible, and make this housekeeping-interval as big as possible ((it's like 25-30% of cpu usage ))

**Comment by nmiculinic** [comment]
Also, what you think of an idea to stip (optionally) metrics completely since I don't care about them that much in this usecase I'm having.

**Comment by eradnab** [comment]
--kubelet-arg=volume-stats-agg-period=10m \
  --kubelet-arg=housekeeping-interval=30s \

Are these options supported in v1.23.9+k3s1? Because I get no errors, but I don't know how to tell if they have applied.

**Comment by brandond** [comment]
Check the upstream kubelet docs for valid flags.
