### ISSUE TITLE
Please add os native package options

### ISSUE THREAD

**Issue by giant-atomic-monster** [k3s-io/k3s#630]
I think official deb and rpm packages for installing k3s would add both ease of use and security.

Signed debs in a ppa and rpms in a yum repository would let end users use `apt` or `yum` to install k3s and let the tooling handle downloading the packages and validate their signatures. This would make it easier to install (not that the current install is hard, it's just not consistent with how everything else is installed), add security since `apt` and `yum` would both validate package signatures before installing and also make uninstalling easier.

**Comment by unixorn** [comment]
Ugh. Used my work account to create the issue by mistake, please @ my unixorn account instead of giant-atomic-monster.

**Comment by matlec** [comment]
+1
Many IoT devices use Debian-based distributions and having deb packages of k3s would help with license compliance (image builders like [Elbe](https://github.com/Linutronix/elbe) already provide a lot of tooling around deb packages)

**Comment by rzr** [comment]
Is dapper mandatory to build k3s ?
https://github.com/rancher/dapper

If yes then this tool should be packaged 1st in debian (to land in ubuntu, raspbian etc)

**Comment by erikwilson** [comment]
It is not required to use dapper to build k3s, it is just a convenient tool we use for setting up requirements for ci/cd & dev in a docker environment. 

The Makefile will also download dapper if it does not already exist in the build directory. 

My main concern is with build stuff getting out of sync, it might be nice if we could provide deb, rpm, & snap in our releases, just as a packaged version of our static binary.

**Comment by rzr** [comment]
Is this page up to date?
https://rancher.com/docs/k3s/latest/en/building/

```sh
./scripts/build
(...)
cmd/server/main.go:7:2: cannot find package "github.com/docker/docker/pkg/reexec" in any of:
```
an alternate makefile would be welcome to automate all needed steps

**Comment by erikwilson** [comment]
It looks like your GOPATH may not be setup correctly, can you compile any go project with vendored packages?

If you follow the ci chain it goes Makefile -> .dapper -> Dockerfile.dapper -> scripts/ci ...

So https://github.com/rancher/k3s/blob/master/scripts/ci is the entry point for running the system, if you follow that you see it will also run scripts/download, scripts/validate, scripts/build, scripts/package (which calls package-cli, package-image, & package-airgap). Instead of an alternative Makefile or targets I think we need to add scripts/package-deb, scripts/package-rpm, and scripts/package-snap logic. 

The requirement for a build machine right now is: git, make, and docker. Dockerfile.dapper will install any required tools as part of the container build process. Whatever utility is needed to build those deb/rpm/snap package files should be installed as part of that Dockerfile.dapper file.

**Comment by brandond** [comment]
Closing due to age.

**Comment by rzr** [comment]
Maybe I can submit a RFS on debian tracker and then crosslink here

**Comment by mohanjith** [comment]
We have published k3s Debian package. See https://launchpad.net/~voyantic/+archive/ubuntu/ppa

**Comment by rzr** [comment]
Next step will be to fill  an RFS/ITP bug to debian tracker

**Comment by siretart** [comment]
Unfortunately, the voyantic package does not meet expectations for inclusion into Debian or ubuntu. It doesn't actually build from source, but instead ships a precompiled executable. As a distribution users, you'd generally expect the package to be built from source with compilers, toolchain, libraries and other components taken from the rest of the distribution.

**Comment by rzr** [comment]
Would packaging to snap or  appimage an alternative option to deliver k3s in binary format ?

**Comment by mildred** [comment]
Things like https://openbuildservice.org/ could be used to generate packages for major distributions allowing installing and upgrading k3s via system packages. This would really be great.

Inclusion within Debian with a build from source would be even better but that's not required for simple users that are willing to configure an extra repo. Moreover, if you want an up to date k3s version, having a dedicated package repository is required.
