### ISSUE TITLE
Upgrade to 1.25 from 1.24 fails (nm-cloud-setup.service not found)

### ISSUE THREAD

**Issue by vasicvuk** [k3s-io/k3s#6366]
**Environmental Info:**
K3s Version: 
```
k3s -v
k3s version v1.24.7+k3s1 (7af5b167)
go version go1.18.7
```

Node(s) CPU architecture, OS, and Version: 
Linux dev-k8s-infra-01 5.15.0-52-generic https://github.com/k3s-io/k3s/pull/51 SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
24 worker nodes (8vCPU, 32gb ram)
2 master (4vCPU 8gb ram)
1 MariaDB database (8vCPU, 32gb ram)
1 nginx load balancer (4vCPU 8gb ram)

**Describe the bug:**
When upgrading from 1.24 to 1.25 k3s service fails to start with following error:
```
Oct 27 11:09:59 dev-k8s-infra-01 sh[1261639]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Oct 27 11:09:59 dev-k8s-infra-01 sh[1261640]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Oct 27 11:10:00 dev-k8s-infra-01 k3s[1261643]: time="2022-10-27T11:10:00Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead."
Oct 27 11:10:00 dev-k8s-infra-01 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Atrox** [comment]
FWIW: the message about `nm-cloud-setup.service` is normal. This is expected and OK. You probably should look at the k3s logs to see what's wrong.

**Comment by brandond** [comment]
It's right there in one of your four log lines.
`level=fatal msg="no-deploy flag is deprecated. Use --disable instead."`

Correct your cli flags as instructed by the error message.

**Comment by vasicvuk** [comment]
Hi @brandond If this is the case, then the error message is wrong. It should not be "flag is deprecated" it should be "flag is removed or replaced by"

**Comment by MacGydver** [comment]
> It hasn't been removed yet. When it's removed you'll get a "unknown flag" error. The flag has been marked as deprecated since v1.17: [0374c4f](https://github.com/k3s-io/k3s/commit/0374c4f63d056df01c3e9e8cf4d77a6461169070) - in 1.25 we have started to actually move towards removing long-deprecated flags, starting with giving specific errors about using their newer equivalents.

I have to disagree with your statement and agree with @vasicvuk 

I just went to upgrade, finally did complete uninstall and try to install from scrach but got the same. When something is "deprecated" it means it can still be used BUT may be removed at any time. In this case it appears to be removed as k3s will not install and start with this option. But changing --no-deploy to --disable I was able to install and start k3s. Since this is the ONLY item I changed to install k3s 1.25 latest, I am 95+% sure this was the issue and that someone may not understand the meaning of deprecated (I get this all the time with product managers and engineers, deprecated sounds more like a term for removed than something that will be removed).
