### ISSUE TITLE
Remove Wireguard backend from release 1.26

### ISSUE THREAD

**Issue by rbrtbnfgl** [k3s-io/k3s#6440]
**Is your feature request related to a problem? Please describe.**

Remove `wireguard` backend after its deprecation #5391

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rancher-max** [comment]
### Validated using v1.26.0-r2+k3s1

- Noted before upgrade (using v1.25.4+k3s1) that there were warnings in the k3s logs:
```
Dec 19 18:58:19 ip-172-31-9-66 k3s[2361]: time="2022-12-19T18:58:19Z" level=warning msg="Flannel is using external addresses with an insecure backend: wireguard. Please consider using an encrypting flannel backend."
Dec 19 18:58:19 ip-172-31-9-66 k3s[2361]: time="2022-12-19T18:58:19Z" level=warning msg="The wireguard backend is deprecated and will be removed in k3s v1.26, please switch to wireguard-native. Check our docs for information about how to migrate"
```
- Upgrade failed as expected due to following fatal error:
```
Dec 19 19:01:09 ip-172-31-9-66 k3s[5502]: time="2022-12-19T19:01:09Z" level=fatal msg="The wireguard backend was deprecated in K3s v1.26, please switch to wireguard-native. Check our docs at docs.k3s.io/installation/network-options for information about how to migrate."
```
- Followed the steps from https://docs.k3s.io/installation/network-options#migrating-from-wireguard-or-ipsec-to-wireguard-native and after rebooting the nodes, upgrade was successful and all the nodes were now running v1.26.0-rc2+k3s1
