### ISSUE TITLE
Change IP of existing master - single node / single master

### ISSUE THREAD

**Issue by bodleytunes** [k3s-io/k3s#6524]
Hi,

This might be impossible, but I have a single node / single master k3s with single node etcd server thats been running happily for over a year in my home setup and I really needed to change the IP address of this machine (actually a VM).

I tried running the k3s init command again like I would do if upgrading k3s binaries but just changed the IP's; but now the service wont start because etcd is expecting the old ip address, and as nothing is starting (chicken and egg), I'm not sure how to delete that or reset that part of the cluster.

I ideally want to keep the state of all the pods, storage etc, but just reset the parts of the cluster information that pertains to the ip address of the master if thats possible?

```
time="2022-11-19T15:07:05Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [rancher2-324a29e7=https://10.89.10.44:2380], expect: rancher2-324a29e7=https://10.89.200.44:2380"
```

Thanks!

Jon.

**Comment by bodleytunes** [comment]
OK it seems I made everything worse. I tried to rollback by changing the IP's back to what they were then running the cluster reset command as follows:

```
/usr/local/bin/k3s server --cluster-init --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/k3s/server/db/snapshots/etcd-snapshot-rancher2-1668729600 --token=mytoken! --debug
```

 and get this:

```
{"level":"warn","ts":"2022-11-19T16:47:58.251Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":73573840,"snapshot-file-path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/000000000462a5d0.snap.db","error":"snap: snapshot file doesn't exist"}
{"level":"panic","ts":"2022-11-19T16:47:58.252Z","caller":"etcdserver/server.go:515","msg":"failed to recover v3 backend from snapshot","error":"failed to find database snapshot file (snap: snapshot file doesn't exist)","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.NewServe
```

Unfortunatly I didn't back up this VM :( 

Cheers!
Jon.

**Comment by bodleytunes** [comment]
Maybe some kind of mismatch, its saying the snap.db file doesn't exist but there is a .snap file which looks similar

<img width="472" alt="image" src="https://user-images.githubusercontent.com/619239/202865524-7c983092-5061-4bc1-afd9-ecc24dd80f99.png">

**Comment by brandond** [comment]
Just do a cluster-reset without restoring. You don't have a full snapshot to restore from - the .snap files you found are not full snapshots, just checkpoint files.

**Comment by bodleytunes** [comment]
OK I will give that a go, thanks!

**Comment by bodleytunes** [comment]
Just wondering, whats the command for this?

I tried the following:

```/usr/local/bin/k3s server --cluster-reset
```

and got the same:

```
WARN[0000] remove /var/lib/rancher/k3s/agent/etc/k3s-agent-load-balancer.json: no such file or directory
WARN[0000] remove /var/lib/rancher/k3s/agent/etc/k3s-api-server-agent-load-balancer.json: no such file or directory
INFO[0000] Starting k3s v1.24.7+k3s1 (7af5b167)
INFO[0000] Managed etcd cluster bootstrap already complete and initialized
INFO[0000] Starting temporary etcd to reconcile with datastore
{"level":"info","ts":"2022-11-19T19:11:56.176Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://127.0.0.1:2400"]}
{"level":"info","ts":"2022-11-19T19:11:56.177Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2399"]}
{"level":"info","ts":"2022-11-19T19:11:56.177Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.3","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.18.7","go-os":"linux","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"rancher2-324a29e7","data-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0.1:2400"],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"info","ts":"2022-11-19T19:11:56.193Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/db","took":"16.081135ms"}
{"level":"info","ts":"2022-11-19T19:11:56.549Z","caller":"etcdserver/server.go:508","msg":"recovered v2 store from snapshot","snapshot-index":73573840,"snapshot-size":"59 kB"}
{"level":"warn","ts":"2022-11-19T19:11:56.552Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":73573840,"snapshot-file-path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/000000000462a5d0.snap.db","error":"snap: snapshot file doesn't exist"}```

**Comment by brandond** [comment]
Is k3s still running at the same time? Does it start up successfully if you don't use cluster-reset? There appear to be some critical missing files...

**Comment by bodleytunes** [comment]
k3s is stopped, no it doesn't start on its own either.

**Comment by brandond** [comment]
Unfortunately it sounds like the etcd datastore has gotten corrupted. I can't say I've seen this specific error before.

**Comment by bodleytunes** [comment]
This is the part that is surprising me, it looks like its trying to restore but cannot see the file, however the file kind of does exist but the naming is slightly different with this prefix instead?  Is there a way to over ride this?

`{"level":"warn","ts":"2022-11-20T10:59:50.285Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":73573840,"snapshot-file-path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/000000000462a5d0.snap.db","error":"snap: snapshot file doesn't exist"}`

vs the actual files

```
root@rancher2:/var/lib/rancher/k3s/server/db/etcd/member/snap# ls -lahs
total 19M
1.5K drwx------ 2 root root   8 Nov 20 11:04 .
 512 drwx------ 4 root root   4 Nov 19 15:46 ..
 56K -rw-r--r-- 1 root root 56K Nov 20 10:29 0000000000000084-000000000462098c.snap
 56K -rw-r--r-- 1 root root 56K Nov 20 10:29 0000000000000084-000000000462309d.snap
 56K -rw-r--r-- 1 root root 56K Nov 20 10:29 0000000000000084-00000000046257ae.snap
 56K -rw-r--r-- 1 root root 56K Nov 20 10:29 0000000000000084-0000000004627ebf.snap
 58K -rw-r--r-- 1 root root 58K Nov 20 10:29 0000000000000089-000000000462a5d0.snap
 18M -rw------- 1 root root 18M Nov 19 16:01 db
```


It seem to be appending that 00.....89-   prefix to them and then can't find the resulting file?

Cheers,
Jon.

**Comment by bodleytunes** [comment]
OK it was easier than I thought to fix!

I will document the steps if anyone else has similar problems:

```
# IMPORTANT backup the relavent snapshots to /fixing-etcd/snapshots folder
cp -r /var/lib/rancher/k3s/server/db/snapshots/ /fixing-etcd/

# uninstall k3s completely
/usr/local/bin/k3s-uninstall.sh

# install cluster again
curl -fL https://get.k3s.io |  INSTALL_K3S_VERSION=v1.24.7+k3s1   K3S_TOKEN=mytoken  sh -s - --cluster-init   --node-ip 10.89.10.44  --advertise-address 10.89.10.44  --no-deploy traefik  --no-deploy servicelb  --etcd-snapshot-retention=24  --flannel-backend=none  --disable-network-policy  --disable-kube-proxy  --snapshotter=fuse-overlayfs  --kubelet-arg=feature-gates=KubeletInUserNamespace=true  --kube-controller-manager-arg=feature-gates=KubeletInUserNamespace=true  --kube-apiserver-arg=feature-gates=KubeletInUserNamespace=true

# stop k3s service
systemctl stop k3s

# restore etcd
/usr/local/bin/k3s server --cluster-init  --cluster-reset --cluster-reset-restore-path=/usr/local/bin/k3s server --cluster-reset-restore-path=/fixing-etcd/snapshots/etcd-snapshot-rancher2-1667865600  --token=mytoken --debug

# start k3s
systemctl start k3s
```

**Comment by meimeitou** [comment]
just change peer urls in etcd.

```
etcdctl.sh member update f9bb6d881882789c --peer-urls="https://192.168.134.12:2380"
```

**Comment by ivucica** [comment]
@meimeitou Since it's etcd spawned by k3s, how is one intended to do that?

- Due to trying to change from v4 to v6, my error is slightly different: `INFO[0809] Failed to test etcd connection: this server is a not a member of the etcd cluster. Found [some-host-name-cd72cee1=https://10.10.10.240:2380], expect: some-host-name-cd72cee1=https://[fd00:abcd:efff:4850::1]:2380 ` and eventually k3s shuts down
- I have the etcd-client package from Debian, so `etcdctl` binary is whatever's in there (presumably should be able to talk to `etcd` inside `k3s` binary
- This is currently a single node cluster
- Attempted incantation: `etcdctl member update some-host-name-cd72cee1 --peer-urls='https://[fd00:abcd:efff:4850::1]:2380'` fails -- it's unable to connect to the new address specified in `--advertise-address`
- `/var/lib/rancher/k3s/server/db/etcd/config` already lists new `listen-peer-urls`, new `listen-client-http-urls`, `listen-client-urls`, `advertise-client-urls` -- all set to v6 already (with appropriate ports)

Presumably doing this _before_ applying new IPs would break etcd first, but I might try reverting the v4-v6 changes.

However, if I change it after the fact, presumably etcd never starts listening on 2380, and gives up on startup.

How is `etcdctl` supposed to operate? In your example, assuming all other peers are gone, how can etcd be made to listen long enough to change the solo peer's address?

Edit (same day): 

- the previously mentioned failure to connect was due to the bad TLS certs, once I took a closer look at k3s output
- a way to get the members list is to pass for-client-use certs and keys for mTLS for use on the client port (2379):

    ```
    sudo etcdctl member list \
      --cacert=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt \
      --cert=/var/lib/rancher/k3s/server/tls/etcd/client.crt \
      --key=/var/lib/rancher/k3s/server/tls/etcd/client.key \
      --endpoints='https://${ADVERTISE_ADDRESS}:2379
    ```

- this will output the existing config, including the member ID; talking to `2379` but setting peers to `2380`:

    ```
    sudo etcdctl member list \
      --cacert=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt \
      --cert=/var/lib/rancher/k3s/server/tls/etcd/client.crt \
      --key=/var/lib/rancher/k3s/server/tls/etcd/client.key \
      --endpoints='https://${ADVERTISE_ADDRESS}:2379 \
      aaaaaaaaaaaaaa \
      --peer-urls='https://[fd00:abcd:efff:4850::1]:2380,https://10.10.10.240:2380'
    ```

- changing the membership does not update the certs, so `k3s certificate rotate --service etcd` is required
- of course, other certs will be missing it too, so just a general `k3s certificate rotate` helps. For good measure I added IPv6 addresses to `tls-san` as well (I can afford to be _mildly_ lax during initial testing, and I control all the internal addresses in these self-signed certs anyway)
- once everything is correctly set up, things almost work, except PodCIDRs for the node now lack IPv6 -- since that's not editable on a node (even to just expand), I assume I'll either really have to rebuild the "cluster", or somehow disable checks that make the field readonly (temporarily), or dig into the config via `etcdctl`; this is obviously not ideal

Again: not production, it's a single node, this was a learning exercise, I don't recommend this approach to migrating v4->dualstack to anyone.

---

@bodleytunes @brandond Is `--cluster-reset` only impacting etcd (and presumably sqlite etc if they were in use)? Does it impact only the configuration but not the data?

Edit (same day): The documentation slightly implies this is so, but I think I needed to pass a snapshot first.
