### ISSUE TITLE
etcd-snapshot-cron flag help text incorrect

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#6752]
* From @akose73 in https://github.com/rancher/rke2-docs/pull/38:
> In the case of "* */5 * * *", it runs every minute past every 5 hours, so it is not true that it runs every 5 hours.
> To solve it set 0 as minutes (0 */5 * * *)

**Comment by VestigeJ** [comment]
This validation isn't super serious because both the previous and now the new example for cron are valid cron schedules.

##Environment Details
COMMIT=ee007bc7cf6b44f863ec0767a6f3155dbd90d54c

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
 
*Cluster Configuration:*
```
NAME              STATUS   ROLES                       AGE   VERSION
ip-222-33-33-44   Ready    control-plane,etcd,master   12m   v1.26.1+k3s-ee007bc7 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: mango
cluster-init: true
snapshot-compress: true
etcd-snapshot-retention: 18
etcd-snapshot-schedule-cron: "*/1 * * * *" //additionally tested "0/1 * * * *"
```

<details>
<summmary><h4> YOUR_REPRODUCED_RESULTS_HERE </h4></summary>



$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/60-rke2-cis.conf
$ sudo cp 60-rke2-cis.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ COMMIT=ee007bc7cf6b44f863ec0767a6f3155dbd90d54c
$ sudo INSTALL_K3S_COMMIT=$COMMIT INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ w2 sudo ls -lahr /var/lib/rancher/k3s/server/db/snapshots/ //watch -n 2 snapshots directory
```

**Results:**

$ sudo ls /var/lib/rancher/k3s/server/db/snapshots/
```
etcd-snapshot-ip-222-33-33-44-1675730044  etcd-snapshot-ip-222-33-33-44-1675730401  etcd-snapshot-ip-222-33-33-44-1675730762
etcd-snapshot-ip-222-33-33-44-1675730100  etcd-snapshot-ip-222-33-33-44-1675730463  etcd-snapshot-ip-222-33-33-44-1675730821
etcd-snapshot-ip-222-33-33-44-1675730162  etcd-snapshot-ip-222-33-33-44-1675730523  etcd-snapshot-ip-222-33-33-44-1675730881
etcd-snapshot-ip-222-33-33-44-1675730224  etcd-snapshot-ip-222-33-33-44-1675730582  etcd-snapshot-ip-222-33-33-44-1675730940
etcd-snapshot-ip-222-33-33-44-1675730282  etcd-snapshot-ip-222-33-33-44-1675730641  etcd-snapshot-ip-222-33-33-44-1675731000
etcd-snapshot-ip-222-33-33-44-1675730342  etcd-snapshot-ip-222-33-33-44-1675730701  etcd-snapshot-ip-222-33-33-44-1675731063
```

</details>
