### ISSUE TITLE
longhorn support for k3s docker image (in k3d)

### ISSUE THREAD

**Issue by 4p00rv** [k3s-io/k3s#6803]
**Environmental Info:**
K3s Version:  rancher/k3s:v1.25.5-k3s2
```
k3s version v1.25.5+k3s2 (de654222)
```

Node(s) CPU architecture, OS, and Version: NA

Cluster Configuration: NA

**Describe the bug:**

When trying to run Lonhorn using k3d on k3s docker image following errors are encountered:
```
isciadm command not found
```
Also, since the image doesn't have a `mount` executable at `/bin/` location `nsenter` is not able to execute it in k3s container.
```
 nsenter [--mount=/host/proc/1/ns/mnt mount], output , stderr nsenter: failed to execute mount: No such file or directory\n: exit status 127"
 ```

**Steps To Reproduce:**

- Setup a `k3d` cluster using `k3d cluster create -v $HOME/longhorn:/var/lib/longhorn:shared@all`
- Install Longhorn using helm

**Expected behavior:**
All contianers are running

**Actual behavior:**

longhorn-manager pod errors out
**Additional context / logs:**

**Comment by brandond** [comment]
> When trying to run Lonhorn using k3d on k3s docker image following errors are encountered:
> `isciadm command not found`

We're not planning on adding extra tools to the k3s image at this time. K3s is intentionally minimalistic; if you want to create an other image based on the k3s image and add tools like iscsiadm to it you are welcome to do do so. k3d allows you to use any image you want; it doesn't have to be ours.

> Also, since the image doesn't have a mount executable at /bin/ location nsenter is not able to execute it in k3s container.

I don't think it's erroring out because of a missing mount command; mount is available in the default path at `/bin/aux/mount` and the command is not specifying `/bin/mount` but just `mount` so it should find it. I suspect that the real problem has something to do with profcs mount propagation from the real underlying host.
