### ISSUE TITLE
how to migrate master to another machine？

### ISSUE THREAD

**Issue by Ehco1996** [k3s-io/k3s#701]

**Comment by tbrandstetter** [comment]
Another requirement, but is also related to "master downtime":

What is the best way to update the operating system (with restart) on a single master? Did a Google Search but found nothing (also no Kubernetes related documents).

**Comment by Ehco1996** [comment]
@tbrandstetter 

i finally migrate data by my self ,it means i shutdown the master node ,then let worker node join to another master node

---

 if only have one master node , it just can't rolling update..
but in k8s you can update master node one by one (during the time ,you service is still in good)

**Comment by zaibon** [comment]
@Ehco1996 could you give more detail about your full setup ?
Did you already had multiple master setup in your cluster ?

I currently have a single master cluster. I would like to move the master to a new node, is there a procedure I can follow to do this ?

**Comment by Ehco1996** [comment]
@zaibon 

my new cluster still have one master

i just create a new master node，and join node one by one manually

**Comment by zaibon** [comment]
@Ehco1996 allright thanks. So I guess that means you start from scratch with a fresh cluster ? Or you managed to keep some sort of state ?

**Comment by Ehco1996** [comment]
@zaibon yes, i just mv my all depolyment and yaml to a new cluster

**Comment by Bwvolleyball** [comment]
What about any of your persistent volumes / data? I'm currently trying to find a migration guide from a single master k3s install to a HA install w/ 3 masters. I recently got a 3rd server, so I finally have the hardware I need to run an HA k3s install.

I'm hoping to do this without data loss if possible.

**Comment by brandond** [comment]
We do not currently have any tools to migrate data between storage backends.

**Comment by eumel8** [comment]
@Bwvolleyball which StorageClass? 

If you use `rancher.io/local-path` you create PV/PVC with the same name on the new cluster and copy the data from the HostPath.Path directory, i.e. `/var/lib/rancher/k3s/storage/pvc-3a653efe-daf5-49a6-b7df-c4139ddf3066_default_repo` 

If you use `openebs.io/provisioner-iscsi` it's the same procedure with data, i.e. `/var/lib/kubelet/pods/251ab868-ff38-4d97-843a-5d26846a660c/volumes/kubernetes.io~iscsi/pvc-1559a3f5-f67e-45ad-950d-710d03a4db0f/`

The last play is with `driver.longhorn.io`. 

- Install Rancher's Longhorn App on both clusters with a replica of 1. 
- Create PV/PVC with the same name, delete workload and detach volumes on the source to get a persistant state. 
- Copy all files under a replica dir to the new cluster (with the different uuid). i.e.  `scp  /var/lib/longhorn/replicas/repo-4e36b273/* server2:/var/lib/longhorn/replicas/repo-c21fa0cb/`
- Attach volume in Longhorn on the server2  and create workload. The data should appear in PVC.

But this method is unsupported. A better approach would be a multi-cluster functionality by Longhorn as requested here: https://github.com/longhorn/longhorn/issues/633 Not sure if Rancher will continue on this issue from 2019 because the multi-cluster-app structure is completly reworked in Rancher 2.5.

**Comment by Bwvolleyball** [comment]
I guess that makes sense. I'm not using Rancher to manage my cluster though, just a direct k3s install. Thanks for the advice!
