### ISSUE TITLE
Investigate the commits we have on top of upstream kubernetes to verify if they're still required

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#8035]
We have about 10 commits on top of upstream kuberenetes that we need to apply on top of k8s releases, we should go through them at a regular cadence to:
A) See if they are upstreamable/should be pushed upstream
B) See if they are still relevant
C) See if they need to be updated to fix conflicts
D) Remove them entirely if they're no longer relevant/needed

**Comment by galal-hussein** [comment]
Note: This comment will be edited with updates for the commits of k3s-io/kubernetes patches.


I will examine patches from version `v1.27.3-k3s1`:

- [ ] Drop client-go cloud auth - [8dbed4f95b5113daafc5987deb4cb40bd0bbfa81](https://github.com/k3s-io/kubernetes/commit/8dbed4f95b5113daafc5987deb4cb40bd0bbfa81)

**Description:**

The commit drops the client-go cloud authentication providers including gcp, azure, and oidc, however azure, gcp in-tree plugins has been removed from client-go code and replaced with stubs.

**Validity:**

This commit is no longer needed since the azure and gcp code has been removed, however further testing is required to see if the oidc code will increase the size of the k3s binary.

**Comment by galal-hussein** [comment]
closing in favor of https://github.com/k3s-io/k3s/issues/2245
