### ISSUE TITLE
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long

### ISSUE THREAD

**Issue by exfly** [k3s-io/k3s#814]
**Describe the bug**

$ vagrant up
```
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
...
```

**Expected behavior**
download box and up the virtualbox

**Screenshots**

**Additional context**
$ vagrant version
Installed Version: 2.1.2
Latest Version: 2.2.5

$ uname -a
Darwin  18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

$ virtualbox

**Comment by galal-hussein** [comment]
@exfly I don't think this issue is related to k3s, you might want to open an issue with `hashicorp/vagrant` if the issue with your vagrant application, thanks.

**Comment by erikwilson** [comment]
The Vagrantfile that is in this repo is for making k3s development easier when using osx, rather than a generic way of trying out k3s @exfly. The failure may be related to the vagrant-alpine or vagrant-timezone plugins, unfortunately issues with using the vagrantfile in this repo is not necessarily something we have the resources to support. If you are interested in using (rather than developing) k3s on OSX then please check out k3d (https://github.com/rancher/k3d), which can be installed via brew.

**Comment by caroline-suse-rancher** [comment]
Closing - appears to be a Vagrant issue
