### ISSUE TITLE
Support for standalone certificate sign service

### ISSUE THREAD

**Issue by mktgbnk** [k3s-io/k3s#8249]
**Is your feature request related to a problem? Please describe.**
Setting up k3s clusters in enterprise environments requires adherence to certain security policies. One common requirement is that all certificates (like those for the apiserver, controller-manager, kubelet, etc.) are signed by the organization's trusted CA. Currently k3s only has an option to use or generate and self-sign these certs.

**Describe the solution you'd like**
Ability to use provided signed certificates for the control and data plane components, without the need to maintain self-signed certificates. The rotation of these certs should be done by cluster operator and not k3s 

**Describe alternatives you've considered**
Following https://docs.k3s.io/cli/certificate#using-custom-ca-certificates still requires a self-generated CA cert and key

**Comment by brandond** [comment]
You are welcome to create the K3s CA certificates however you like. The documentation and example scripts are intended to be a starting point for someone who wants to use an external CA to sign the cluster certificates. It is not expected that the auto-generation logic built into K3s, or the example script, will ever cover all of the possible ways that someone may want to handle PKI.

Note that Kubernetes itself requires CA certificates in order to support the CertificateSigningRequest resource type, so it is not possible to use Kubernetes with only end-entity (client/server) certificates.

The way that K3s handles configuration and certificate generation for the various Kubernetes components is core to how it functions, we do not have any plans to disable the built-in end-entity certificate generation logic and allow the user to provide fixed certificates. If you have a requirement that all of your certificates be generated using an external tool or process, K3s (or RKE2) may not be the right choice for you.
