### ISSUE TITLE
curl install of k3s crashes with mv: cannot move '/tmp/k3s-install.D1qN11bGus/k3s.bin' to '/usr/local/bin/k3s': No such file or directory

### ISSUE THREAD

**Issue by davidthewatson** [k3s-io/k3s#855]
curl install of k3s crashes with:

    mv: cannot move '/tmp/k3s-install.D1qN11bGus/k3s.bin' to '/usr/local/bin/k3s': No such file or directory

**To Reproduce**
1. Install ubuntu 19.04
2. sudo apt update
3. sudo apt upgrade
4. curl -sfL https://get.k3s.io | sh -

**Expected behavior**
k3s installed and perhaps running

Complete log:

```
$ curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v0.9.1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.9.1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.9.1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
mv: cannot move '/tmp/k3s-install.D1qN11bGus/k3s.bin' to '/usr/local/bin/k3s': No such file or directory
```

**Comment by mfonner** [comment]
I'm also seeing this on Ubuntu 19.10.

**Comment by paroque28** [comment]
I had the same issue: 
root@jetson-nano-qspi-sd:~#   curl -sfL https://get.k3s.io | sh -

[INFO]  Finding latest release
[INFO]  Using v1.17.3+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.3+k3s1/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.17.3+k3s1/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
mv: cannot move '/tmp/k3s-install.T6TqgJWGYS/k3s.bin' to '/usr/local/bin/k3s': No such file or directory

Fixed by creating the directory as well

```bash
mkdir /usr/local/bin

```
