### ISSUE TITLE
Consider using AppImage and AppImageUpdate instead of shell script for universal platform support

### ISSUE THREAD

**Issue by sandys** [k3s-io/k3s#871]
This proposal is around replacing shell script with AppImage format. I'm not recommending  any replacement of distro specific packages (deb/rpm)

https://appimage.org  is a packaging tool that makes executable installers that run on every major linux platform. 
They also have built-in update tooling https://docs.appimage.org/packaging-guide/updates.html
AppImages are also signed for security - https://docs.appimage.org/packaging-guide/signatures.html 

They can also be mounted and inspected - https://docs.appimage.org/user-guide/run-appimages.html 

There's already a large list of appimages that are popularly used - https://appimage.github.io/apps/ 

AppImage is an infintely better way to distribute k3s versus shell scripts.

**Comment by erikwilson** [comment]
Sorry, I am trying to understand the advantages of using AppImage versus our current system, can you please elaborate on how it is infinitely better? It appears that we have solved most of the issues AppImage is trying to solve by using static + muslc compilations of k3s (also a self extracting binary). The installation script provides a single line command for installing that k3s binary to systemd or openrc, does AppImage help with that use-case?

**Comment by Atem18** [comment]
@erikwilson You are right, appimage has no relation with the shell scripts that you provide.

But what would be the best is to have linux repos with the binaries inside so we can just update k3s with a yum update or apt update.

**Comment by erikwilson** [comment]
We are certainly happy to help package maintainers create OS specific releases, it looks like Alpine and Arch have some packages currently available:

https://pkgs.alpinelinux.org/packages?name=k3s&branch=edge
https://aur.archlinux.org/packages/k3s-bin/

For the most part we have upstreamed our containerd changes for better arm support. There is some challenge because we tend to test and ship with specific versions of supporting packages that are newer than what may be used in the OS distributions. For instance alpine ships containerd 1.2.9 and strongswan 5.7.2 where we are now shipping containerd 1.3.0 and strongswan 5.8.1 with k3s v0.10.0-alpha1. 

We have considered providing an auto-update feature, perhaps a command like `k3s update/upgrade` could help minimize that effort.

**Comment by sandys** [comment]
Hi
Thank you guys for your comments. Sorry if the intent was lost in the
poorly worded title.

My original purpose for this issue was to address the primary problem of
predictable updates and signing...in a context where the k3s devs won't be
able to support all the myriad packaging formats there are.

Appimage was one. https://cnab.io/ could be other. Not sure if k3s is
viable to be delivered as a docker image itself.

However I wanted to highlight that as k3s goes closer towards prediction
usecases, some sort of robust signing/update/package management features
are needed.

**Comment by erikwilson** [comment]
Who uses CNAB? (serious question) Is it an Azure only thing?
What is needed for it? Just a bundle.json file? How do I use it? 
PRs are welcome! (please see /contrib)

- Updates should be as simple as replacing the binary and restarting. Some update logic could probably be added to roll updates out to nodes.
- Validation of the binary is accomplished at the moment by checking the hash of the executable, if you trust github certs and build process this should be sufficient. 
- Yes there is a k3s docker image, there is also k3os and k3d, please look into those.

I think we should be moving as much functionality from the install script into the k3s binary as possible. I would like to see some commands like the following:

```sh
# validate the binary
k3s verify binary

# validate system requirements
k3s verify system

# install a systemd or openrc service
k3s install (... args ...)

# upgrade k3s
k3s upgrade (version)

# auto-update k3s (download & log but no restart)
k3s auto-update (on|off) (schedule)

# auto-upgrade k3s (download & restart)
k3s auto-upgrade (on|off) (schedule)
```

**Comment by Atem18** [comment]
@erikwilson Are you sure putting more « complex » features does not go against k3s purpose which is to be as light as possible ?

I know that on Windows or Mac OS there is no other choice but on Linux, we have package managers so I think it would be best to use it instead and call for volunteers to maintain packages/repo for each distribution like the guys from alpine and arch Linux does.

What do you think ?

**Comment by erikwilson** [comment]
The commands are light in executable size, memory, and cpu footprint. They may not be ideal from a package maintainer's point of view so could maybe be disabled for distributions. But, they may not be ideal from a cognitive overhead view also either even tho the purpose is to make using k3s easier, so maybe better to stick to the install script. Personally I don't think many people are using the distro packages at the moment, I would prefer to have access to the latest k3s/k8s release rather than wait for it to trickle down through a distro anyways.

**Comment by sandys** [comment]
>Yes there is a k3s docker image, there is also k3os and k3d, please look
into those.

Question in general - why is that not the primary release mechanism for k3s
? does it have a limitation that needs k3s to run natively and through the
script ? If there was a way that docker-based k3s works well, then that
should be the primary release mechanism. docker will give you signing,
updates, versioning...pretty much all the benefits of a package manager.

> I think we should be moving as much functionality from the install script
into the k3s binary as possible. I would like to see some commands like the
following:

totally totally  agree here.

>@erikwilson <https://github.com/erikwilson> Are you sure putting more
« complex » features does not go against k3s purpose which is to be as
light as possible ?

K3s is as simple as possible when it comes to kubernetes. But that does
mean batteries included. It can be argued that k3s should not have network
plugins or ingresses bundled in. But I'm not very sure that a few mb in
size decrease is what will make k3s compelling versus k8s. The problem with
k8s is complexity of getting started and bundling+batteries is
simplification.

I would go as far as to say that even if k3s is double the size of k8s, but
is super simple... that would solve what most people are looking for.

**Comment by caroline-suse-rancher** [comment]
Closing due to age
