### ISSUE TITLE
auto quickstart needs to add iptables or firewall mention

### ISSUE THREAD

**Issue by rbucker** [k3s-io/k3s#873]
generally speaking the main page provides some quickstart and manual installation instructions... but it did not work for me until I added iptables 

```
iptables -A INPUT -p tcp --dport 6443 -j ACCEPT
```

Just an FYI feel free to close

**Comment by drannenberg** [comment]
Hello,
Indeed, in the case where you have INPUT table set to DROP by default, this rule would be mandatory in order to run the agent on another node. However, this line might be too 'open' for a secure environment, it might be more secure to add something like
```
iptables -A INPUT -s `K3S_AGENT_IP` -d `K3S_MASTER_IP` -p tcp --dport 6443 -j ACCEPT
```
Thank you for your comment, a pull request to add this in the documentation has been done https://github.com/rancher/docs/pull/1846

**Comment by erikwilson** [comment]
Thanks for the info & the docs PR! Here are a few thoughts:

- We are currently working on changing how the docs are organized, but this probably should be in it's own section rather than quick-start docs
- It is probably preferable to have firewall specific docs, with iptables specific change as a last resort. If possible we should automate the process and provide a generic command.
- There may be other things that need to be changed, depending on the type of firewall and the order of services that come up.
- iptables based firewalls make me sad :(

**Comment by rbucker** [comment]
@drannenberg I suppose there is something to be said for a static network route map based on ```iptables``` but I think "things" will go sideways very quickly depending on how dynamic the nodes are and how large the network might be. Sure we are just talking about ```k3os``` with a mission of a solo node. So this is as much a marketing or product decision as it is engineering.

**Comment by davidnuzik** [comment]
We are beginning to make some changes and improvements to the k3s docs. We will work to more clearly state what ports/etc need to be open.

**Comment by dereknola** [comment]
This has been completed. Specific ports that need to be opened can be found at https://docs.k3s.io/installation/requirements#networking
