### ISSUE TITLE
DNS Loop for zone "."

### ISSUE THREAD

**Issue by Brav-o** [k3s-io/k3s#9066]
**Environmental Info:**
k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 
5 nodes, each with CPU amd64 and OS ubuntu 22.04

**Describe the bug:**
CoreDNS pods crash constantly and it makes others pods crash. I tried many things for days and I just cant find a permanent fix. If I change the default "forward" rule in the coredns configmap to something like `forward . tls://9.9.9.9` it works, but it get overwritten so it is not very helpful and I dont know if it is possible to make the change permanent.

CoreDNS pods crash with this error message :
`[FATAL] plugin/loop: Loop (127.0.0.1:60292 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 5578201896000263180.6097644536601687215."`

The coredns config map : 
```
.:53 {
    errors
    health
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    hosts /etc/coredns/NodeHosts {
      ttl 60
      reload 15s
      fallthrough
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
    import /etc/coredns/custom/*.override
}
import /etc/coredns/custom/*.server
```

My resolv conf on hosts (same on each server) : 
```
nameserver 1.1.1.1
options edns0 trust-ad
```

The resolv conf on pods :
```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5
```

**Comment by brandond** [comment]
I'm not sure why you would be getting errors from that upstream, but as you noted you can't just directly change the coredns configmap as it is managed by k3s. 

My suggestion would be to either point at a different upstream in the host resolv.conf, or create another resolv.conf just for use by k3s that uses at your desired upstream, and point at that using the `--resolv-conf` option.

**Comment by andrioid** [comment]
In case this helps someone else... I am injecting a resolvd config into `/etc/systemd/resolved.conf.d` so that hosts can resolve cluster addresses out of the box, which is great for stuff like restoring database backups, and what not. However, that seemed to be causing a loop when querying non-existent cluster hostnames.

What worked for me was:
- Generate a simplistic resolv.conf (that doesn't use systemd-resolved) in `/etc/rancher/k3s/resolv.conf`
- Set the resolv-conf to `/etc/rancher/k3s/resolv.conf` in my config (or cli)
- Restart k3s server and kill the CoreDNS pod manually. If that doesn't work, try mutating the ConfigMap for CoreDNS too.
