### ISSUE TITLE
E2E: Embedded Registry test is broken

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#9656]
**Environmental Info:**
K3s Version: Master

Cluster Configuration:

Spiegel enabled cluster

**Describe the bug:**

Current embedded registry test fails and in not running in CI for that reason. 
```
failed to run command: kubectl patch deployment my-webpage-1 --patch '{"spec":{"replicas":2,"revisionHistoryLimit":0,"strategy":{"type":"Recreate", "rollingUpdate": null},"template":{"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["my-webpage-1"]}]},"topologyKey":"kubernetes.io/hostname"}]}}}}}}' on node server-0: Error from server (BadRequest): invalid character 's' looking for beginning of object key string
```

Need to fix up the test and add it back into CI

**Comment by brandond** [comment]
Underlying issue is how the double-quoted string is passed through the vagrant ssh command:
`failed to run command: vagrant ssh server-0 -c "sudo kubectl patch deployment my-webpage-1 --patch '{"spec":{"replicas":2,"revisionHistoryLimit":0,"strategy":{"type":"Recreate", "rollingUpdate": null},"template":{"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["my-webpage-1"]}]},"topologyKey":"kubernetes.io/hostname"}]}}}}}}'"`
