### ISSUE TITLE
tailscale support additional routes

### ISSUE THREAD

**Issue by ysicing** [k3s-io/k3s#9677]
At the moment, it seems that only default own routes are supported, I would like to support additional routes, for example

```
--advertise-routes 10.100.9.0/24,10.142.9.0/24
```

`10.100.9.0/24` is an additional route

**Comment by brandond** [comment]
cc @manuelbuil

**Comment by manuelbuil** [comment]
Yeah, this is not possible right now, it should be treated as a feature request. But it could be done in different ways.

Instead of being able to add extra routes through K3s, I think it might be a better idea that we keep the current configured tailscale subnets. So if you advertise subnet `10.100.9.0/24` because of non-k3s-related reasons, then, when deploying k3s, it should not overwrite that but add the k8s network additionally. We are currently overwriting it because otherwise, things do not work well with tailscale binary. I think we could do this:
1 - You start tailscale by yourself and configure the advertisement of the extra subnet
2 - Start K3s with Tailscale
3 - K3s checks if tailscale is running. If not, it kicks it off as of today
4 - If tailscale is already running, it reads the current tailscale config and re-applies it adding the extra cidr for the pod-pod communication
Would this approach work for you?

**Comment by manuelbuil** [comment]
> tailscale, which has been run, does not appear to be working. ![image](https://private-user-images.githubusercontent.com/8605565/311271366-d3a88ee4-2021-43d1-8d1e-f0ee41885f5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzk0MzMsIm5iZiI6MTcxMDEzOTEzMywicGF0aCI6Ii84NjA1NTY1LzMxMTI3MTM2Ni1kM2E4OGVlNC0yMDIxLTQzZDEtOGQxZS1mMGVlNDE4ODVmNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDYzODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVmMzZiNTlkYzkyZWEzNDAyMDdmMWY2OGMyZDQwOGEyMjA4N2I4MzA5YWJkNmVlMGVjYzgwODA5N2I0Yjk5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZxMHX6nHJksFuQoSG_scObUaPmFfP-ccjwb0hxhnlmQ)

Did you modified the ACL and added that route in the self-approve section?

**Comment by tdtgit** [comment]
@manuelbuil I think your approach to current working Tailscale instance is more sufficient, when we don't want to break Tailnet's connection while stopping k3s.
