### ISSUE TITLE
[question] the VXLAN port on nodes should not be exposed to the world / multi cloud advice

### ISSUE THREAD

**Issue by wc-matteo** [k3s-io/k3s#989]
> it opens up your cluster network to accessed by anyone

What does it mean exactly? What could they do?

I need to implement a multi-cloud (cloud = vps like DO, in this case) kubernetes cluster. What would be the best way to make nodes communicate while still keeping things secure? Is running a _single_ cluster across multiple cloud providers something that's discouraged?

> k3s uses reverse tunneling such that the nodes make outbound connections to the server and all kubelet traffic runs through that tunnel

Does this mean that the traffic of an app running inside the cluster passes both through the "worker node" (where the app is running) and the "master node"? If that's the case, when master and worker are on different cloud providers, that would mean _consuming_ traffic in both places, right?

Sorry if this is not the place. I saw other issues containing some of these topics but I didn't see any definitive advice on this.

**Comment by wc-matteo** [comment]
cc @erikwilson

**Comment by erikwilson** [comment]
https://www.troopers.de/troopers19/agenda/hv7ywt/

**Comment by erikwilson** [comment]
The behavior of the tunnel is independent of the networking setup. The tunnel allows master to agent communication while the network allows pod to pod communication (services that pods on different nodes can access).

If you haven't already it may be helpful to checkout Rancher's multi-cluster apps, where maybe you can run workloads across multiple clusters instead of a single cluster. 

I would like to get a multi-cloud setup or better NAT working out of the box for k3s, but not sure when/if it would happen.

**Comment by erikwilson** [comment]
Yes, ipsec will secure the network traffic, there is probably more that needs to be done code-wise to make NAT work tho.
