### ISSUE TITLE
Expose K3s metrics via supervisor port

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#9951]
K3s tracking issue for
* https://github.com/rancher/rke2/issues/5786

We'll need to refactor things a bit on the k3s side to allow starting up the supervisor listener and exposing the Prometheus gatherer at /metrics even if Spegel isn't enabled. Currently that stuff is all wrapped inside the spegel handler-getter function that is only run when the embedded registry is enabled:
https://github.com/k3s-io/k3s/blob/06b6444904294c415b314c78c41cf424e7e749d6/pkg/cli/agent/agent.go#L108-L113

This won't really add much on K3s, since it'll just be another place to get the same metrics that are already mixed in via all the other /metrics endpoints that share the same Kubernetes registerer/gatherer... but it is needed for RKE2 where we can't reuse the existing Kubernetes metrics endpoints to export our metrics.

**Comment by aganesh-suse** [comment]
### Validated on master branch with commit d9b8ba8d7109ca098c379d170eb412879c5ee94e
 
## Environment Details

 
*Infrastructure*
- [x] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
 
*Cluster Configuration:*

```
HA: 3 server/ 1 agent
```
 
*Config.yaml:*

Server Config: 
```
token: xxxx
cluster-init: true
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
node-label:
- k3s-upgrade=server
debug: true

supervisor-metrics: true
enable-pprof: true
```

Agent Config: 
```
token: xxxx
server: https://1.1.1.1:6443
node-external-ip: 1.1.1.2
node-label:
- k3s-upgrade=agent
debug: true

enable-pprof: true
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
```
curl -sfL https://get.k3s.io | sudo INSTALL_K3S_COMMIT='d9b8ba8d7109ca098c379d170eb412879c5ee94e' sh -s - server
```
3. Verify Cluster Status: 
```
kubectl get nodes -o wide
kubectl get pods -A
```
4. Query /metrics and /debug/pprof 

 
 
**Validation Results:**
- k3s version used for validation:

```
$ k3s -v
k3s version v1.30.1+k3s-d9b8ba8d (d9b8ba8d)
go version go1.22.2
```
 

The following queries work on both server and agent nodes. Not providing output due to size. 
```
 $ sudo curl -vks --cert /var/lib/rancher/k3s/server/tls/client-admin.crt --key /var/lib/rancher/k3s/server/tls/client-admin.key https://<server|agent ip>:6443/metrics 
  $ sudo curl -vks --cert /var/lib/rancher/k3s/server/tls/client-admin.crt --key /var/lib/rancher/k3s/server/tls/client-admin.key https://<server|agent ip>:6443/debug/pprof
```
